// inertia/pages/parishes.vue
<template>
  <Head title="Nos Paroisses" />

  <PageBanner bg-color="bg-gradient-to-r from-catholic-purple to-catholic-blue" py="16">
    <h1 class="text-4xl md:text-5xl font-bold mb-4 font-serif">Nos Paroisses</h1>
    <p class="text-xl opacity-90">
      Découvrez les communautés de foi qui composent notre archidiocèse
    </p>
  </PageBanner>

  <section class="py-16">
    <div class="container max-w-7xl mx-auto px-4">
      <Typography variant="h2" class="pb-10 text-catholic-purple font-bold">
        Doyenné Notre-Dame-des-Saints
      </Typography>
      <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
        <Card v-for="parish in parishes" :key="parish.id" class="card-hover pt-0">
          <div
            v-if="parish.image"
            class="aspect-video bg-cover bg-center"
            :style="`background-image: url(${parish.image})`"
          ></div>
          <div v-else class="aspect-video bg-gray-200 rounded-t-lg"></div>
          <CardContent class="p-6">
            <h3 class="font-bold text-xl mb-2 text-catholic-purple">{{ parish.name }}</h3>
            <div class="flex items-start gap-2 mb-3 text-sm text-gray-600">
              <MapPin class="w-4 h-4 mt-0.5 flex-shrink-0" />
              <span>{{ parish.address }}</span>
            </div>

            <p class="text-base text-justify leading-7 py-2">{{ parish.description }}</p>

            <div class="mb-4">
              <h4 class="inline font-semibold mb-2 text-sm">{{ parish.priestOffice }} :</h4>
              <div class="inline ml-2 space-y-1 text-xs">
                {{ parish.priestName }}
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import PageBanner from '@/components/layout/PageBanner.vue'
import { Card, CardContent } from '@/components/ui/card'
import Head from '@/components/AppHead.vue'
import { MapPin } from 'lucide-vue-next'
import { parishes } from '@/constants/parishes.constants'
import { Typography } from '@/components/ui/typography'
</script>

// src/routes/_app/parishes.tsx
import { createFileRoute } from '@tanstack/react-router'
import { parishes } from '#/config/parishes.ts'
import { ParishesExplorer } from '#/features/parishes/components/parishes-explorer'
import { pageMetadata } from '#/utils/seo.ts'
import Hero from '#shared/layouts/app/components/hero.tsx'

export const Route = createFileRoute('/_app/parishes')({
  head: () => ({
    meta: pageMetadata('Nos Paroisses', {
      metadata: {
        description: "Découvrez les communautés de foi qui composent l'archidiocèse de Los Santos.",
      },
    }),
  }),
  component: ParishesPage,
})

function ParishesPage() {
  return (
    <>
      <Hero
        variant="minimal"
        title="Nos Paroisses"
        backgroundColor="bg-linear-to-r from-catholic-purple to-catholic-blue"
        subtitle="Découvrez les communautés de foi qui composent l'archidiocèse de Los Santos."
      />

      <section className="container mx-auto max-w-7xl px-4 pt-15 pb-20 sm:px-6 lg:px-8">
        <header className="mb-10 max-w-3xl">
          <p className="mt-4 leading-relaxed text-muted-foreground">
            Les paroisses de l'archidiocèse de Los Santos vous accueillent pour les célébrations,
            les sacrements et la vie de quartier. Sélectionnez une paroisse pour la localiser sur la
            carte.
          </p>
        </header>

        <div className="mb-8 flex flex-wrap items-center gap-x-6 gap-y-2 border-b border-border pb-6 text-sm text-muted-foreground">
          <span className="font-semibold text-foreground">{parishes.length} paroisses</span>
          <span aria-hidden className="text-border">
            ·
          </span>
          <span>Doyenné Notre-Dame-des-Saints</span>
        </div>

        <ParishesExplorer />
      </section>
    </>
  )
}
