// inertia/shared/components/ui/markdown-textarea.tsx
import { cn } from '@/lib/utils'
import { ComponentProps, useCallback, useRef } from 'react'
import { Textarea } from '@/shared/components/ui/textarea'
import { Button } from '@/shared/components/ui/button'
import { Separator } from '@/shared/components/ui/separator'
import {
  Bold,
  Heading2,
  Heading3,
  Image,
  Italic,
  Link,
  List,
  ListOrdered,
  Minus,
  Quote,
} from 'lucide-react'

type MarkdownTextareaProps = Omit<ComponentProps<typeof Textarea>, 'onChange'> & {
  onChange?: (value: string) => void
}

type ToolbarAction = {
  icon: React.ReactNode
  label: string
  action: (textarea: HTMLTextAreaElement, onChange?: (value: string) => void) => void
}

function applyChange(
  textarea: HTMLTextAreaElement,
  newValue: string,
  cursorStart: number,
  cursorEnd: number,
  onChange?: (value: string) => void
) {
  onChange?.(newValue)
  requestAnimationFrame(() => {
    textarea.setSelectionRange(cursorStart, cursorEnd)
    textarea.focus()
  })
}

function wrapSelection(
  textarea: HTMLTextAreaElement,
  before: string,
  after: string,
  placeholder: string,
  onChange?: (value: string) => void
) {
  const start = textarea.selectionStart
  const end = textarea.selectionEnd
  const selected = textarea.value.substring(start, end) || placeholder
  const newValue =
    textarea.value.substring(0, start) + before + selected + after + textarea.value.substring(end)
  const newCursor = start + before.length + selected.length + after.length
  applyChange(textarea, newValue, newCursor, newCursor, onChange)
}

function prependLine(
  textarea: HTMLTextAreaElement,
  prefix: string,
  placeholder: string,
  onChange?: (value: string) => void
) {
  const start = textarea.selectionStart
  const lineStart = textarea.value.lastIndexOf('\n', start - 1) + 1
  const hasPrefix = textarea.value.substring(lineStart).startsWith(prefix)

  if (hasPrefix) {
    const newValue =
      textarea.value.substring(0, lineStart) + textarea.value.substring(lineStart + prefix.length)
    const newCursor = Math.max(lineStart, start - prefix.length)
    applyChange(textarea, newValue, newCursor, newCursor, onChange)
  } else {
    const selected =
      textarea.value.substring(textarea.selectionStart, textarea.selectionEnd) || placeholder
    const newValue =
      textarea.value.substring(0, lineStart) +
      prefix +
      selected +
      textarea.value.substring(textarea.selectionEnd)
    const newCursor = lineStart + prefix.length + selected.length
    applyChange(textarea, newValue, newCursor, newCursor, onChange)
  }
}

function insertLink(textarea: HTMLTextAreaElement, onChange?: (value: string) => void) {
  const start = textarea.selectionStart
  const end = textarea.selectionEnd
  const selected = textarea.value.substring(start, end) || 'texte du lien'
  const insertion = `[${selected}](url)`
  const newValue = textarea.value.substring(0, start) + insertion + textarea.value.substring(end)
  const urlStart = start + selected.length + 3
  applyChange(textarea, newValue, urlStart, urlStart + 3, onChange)
}

function insertImage(textarea: HTMLTextAreaElement, onChange?: (value: string) => void) {
  const start = textarea.selectionStart
  const end = textarea.selectionEnd
  const selected = textarea.value.substring(start, end) || 'description'
  const insertion = `![${selected}](url)`
  const newValue = textarea.value.substring(0, start) + insertion + textarea.value.substring(end)
  const urlStart = start + selected.length + 4
  applyChange(textarea, newValue, urlStart, urlStart + 3, onChange)
}

function insertHorizontalRule(textarea: HTMLTextAreaElement, onChange?: (value: string) => void) {
  const start = textarea.selectionStart
  const insertion = '\n---\n'
  const newValue = textarea.value.substring(0, start) + insertion + textarea.value.substring(start)
  const newCursor = start + insertion.length
  applyChange(textarea, newValue, newCursor, newCursor, onChange)
}

export function MarkdownTextarea({
  id,
  value = '',
  onChange,
  placeholder = 'Écrivez votre contenu en Markdown...',
  disabled = false,
  className,
  rows = 5,
  ...props
}: MarkdownTextareaProps) {
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  const handleAction = useCallback(
    (action: (ta: HTMLTextAreaElement, cb?: (v: string) => void) => void) => {
      if (textareaRef.current) action(textareaRef.current, onChange)
    },
    [onChange]
  )

  const toolbarGroups: ToolbarAction[][] = [
    [
      {
        icon: <Bold className="size-3.5" />,
        label: 'Gras',
        action: (ta, cb) => wrapSelection(ta, '**', '**', 'texte en gras', cb),
      },
      {
        icon: <Italic className="size-3.5" />,
        label: 'Italique',
        action: (ta, cb) => wrapSelection(ta, '_', '_', 'texte en italique', cb),
      },
    ],
    [
      {
        icon: <Heading2 className="size-3.5" />,
        label: 'Titre 2',
        action: (ta, cb) => prependLine(ta, '## ', 'Titre', cb),
      },
      {
        icon: <Heading3 className="size-3.5" />,
        label: 'Titre 3',
        action: (ta, cb) => prependLine(ta, '### ', 'Titre', cb),
      },
      {
        icon: <Quote className="size-3.5" />,
        label: 'Citation',
        action: (ta, cb) => prependLine(ta, '> ', 'Citation', cb),
      },
    ],
    [
      {
        icon: <List className="size-3.5" />,
        label: 'Liste',
        action: (ta, cb) => prependLine(ta, '- ', 'Élément', cb),
      },
      {
        icon: <ListOrdered className="size-3.5" />,
        label: 'Liste numérotée',
        action: (ta, cb) => prependLine(ta, '1. ', 'Élément', cb),
      },
    ],
    [
      {
        icon: <Link className="size-3.5" />,
        label: 'Lien',
        action: insertLink,
      },
      {
        icon: <Image className="size-3.5" />,
        label: 'Image',
        action: insertImage,
      },
      {
        icon: <Minus className="size-3.5" />,
        label: 'Séparateur',
        action: insertHorizontalRule,
      },
    ],
  ]

  return (
    <div className={cn('rounded-md border bg-background', className)}>
      <div className="flex flex-wrap items-center gap-0.5 border-b px-2 py-1.5">
        {toolbarGroups.map((group, i) => (
          <div key={i} className="flex items-center gap-0.5">
            {i > 0 && <Separator orientation="vertical" className="mx-1 h-4" />}
            {group.map((tool) => (
              <Button
                key={tool.label}
                type="button"
                variant="ghost"
                size="sm"
                className="h-7 w-7 p-0"
                title={tool.label}
                disabled={disabled}
                onClick={() => handleAction(tool.action)}
              >
                {tool.icon}
                <span className="sr-only">{tool.label}</span>
              </Button>
            ))}
          </div>
        ))}
      </div>

      <Textarea
        ref={textareaRef}
        id={id}
        value={value}
        onChange={(e) => onChange?.(e.target.value)}
        placeholder={placeholder}
        disabled={disabled}
        style={{ minHeight: `${rows * 24}px` }}
        className="rounded-t-none border-0 font-mono text-sm shadow-none focus-visible:ring-0 resize-y"
        {...props}
      />
    </div>
  )
}

// inertia/components/ui/markdown/MarkdownTextarea.vue
<template>
  <div :class="cn('relative w-full', props.class)">
    <!-- Toolbar -->
    <div v-if="!disabled" class="flex items-center gap-1 mb-2 p-2 border rounded-md bg-muted/50">
      <Button
        variant="ghost"
        type="button"
        @click="insertMarkdown('**', '**')"
        class="p-1.5 hover:bg-muted rounded text-sm font-semibold"
        title="Gras (Ctrl+B)"
      >
        B
      </Button>
      <Button
        variant="ghost"
        type="button"
        @click="insertMarkdown('_', '_')"
        class="p-1.5 hover:bg-muted rounded text-sm italic"
        title="Italique (Ctrl+I)"
      >
        I
      </Button>
      <Button
        variant="ghost"
        type="button"
        @click="insertMarkdown('# ')"
        class="p-1.5 hover:bg-muted rounded text-sm font-bold"
        title="Titre"
      >
        H
      </Button>
      <Button
        variant="ghost"
        type="button"
        @click="insertMarkdown('- ')"
        class="p-1.5 hover:bg-muted rounded text-sm"
        title="Liste"
      >
        •
      </Button>
      <Button
        variant="ghost"
        type="button"
        @click="insertMarkdown('![Alt text](image-url)')"
        class="p-1.5 hover:bg-muted rounded text-sm"
        title="Image"
      >
        🖼️
      </Button>
      <Button
        variant="ghost"
        type="button"
        @click="insertMarkdown('[](url)')"
        class="p-1.5 hover:bg-muted rounded text-sm"
        title="Lien"
      >
        🔗
      </Button>
      <Button
        variant="ghost"
        type="button"
        @click="insertMarkdown('`', '`')"
        class="p-1.5 hover:bg-muted rounded text-sm font-mono"
        title="Code"
      >
        &lt;/&gt;
      </Button>

      <div class="flex-1"></div>

      <Button
        variant="ghost"
        v-if="preview"
        type="button"
        @click="togglePreview"
        :class="
          cn(
            'p-1.5 rounded text-sm',
            showPreview ? 'bg-primary text-primary-foreground' : 'hover:bg-muted'
          )
        "
        title="Aperçu"
      >
        👁
      </Button>
    </div>

    <!-- Editor / Preview -->
    <div class="relative">
      <textarea
        v-show="!showPreview"
        ref="textareaRef"
        v-model="localValue"
        :disabled="disabled"
        :placeholder="placeholder"
        :rows="rows"
        @keydown="handleKeyDown"
        @blur="emit('blur', $event)"
        @focus="emit('focus', $event)"
        :class="
          cn(
            'flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2',
            'text-sm ring-offset-background placeholder:text-muted-foreground',
            'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
            'disabled:cursor-not-allowed disabled:opacity-50',
            'resize-y font-mono'
          )
        "
      />

      <div
        v-show="showPreview"
        :class="
          cn(
            'min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2',
            'overflow-auto'
          )
        "
        :style="{ minHeight: `${rows * 1.5}rem` }"
      >
        <MarkdownContent v-if="localValue" :content="localValue" class="max-w-none" />
        <p v-else class="text-muted-foreground text-sm">Aucun contenu à prévisualiser...</p>
      </div>
    </div>

    <!-- Aide Markdown -->
    <div class="mt-2 text-xs text-muted-foreground">
      <span class="font-mono">**gras**</span> • <span class="font-mono">_italique_</span> •
      <span class="font-mono"># titre</span> • <span class="font-mono">- liste</span> •
      <span class="font-mono">`code`</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { cn } from '@/lib/utils'
import { MarkdownContent } from '@/components/ui/markdown'
import { Button } from '@/components/ui/button'

interface Props {
  modelValue?: string
  placeholder?: string
  disabled?: boolean
  class?: string
  rows?: number
  preview?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: '',
  placeholder: 'Écrivez votre contenu en Markdown...',
  disabled: false,
  rows: 10,
  preview: true,
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
  'blur': [event: FocusEvent]
  'focus': [event: FocusEvent]
}>()

const showPreview = ref(false)
const textareaRef = ref<HTMLTextAreaElement>()

const localValue = computed({
  get: () => props.modelValue,
  set: (val) => emit('update:modelValue', val),
})

const togglePreview = () => {
  showPreview.value = !showPreview.value
}

const insertMarkdown = (before: string, after = '') => {
  const textarea = textareaRef.value
  if (!textarea) return

  const start = textarea.selectionStart
  const end = textarea.selectionEnd
  const text = localValue.value
  const selectedText = text.substring(start, end)

  localValue.value = text.substring(0, start) + before + selectedText + after + text.substring(end)

  // Restaurer la sélection
  setTimeout(() => {
    textarea.focus()
    textarea.setSelectionRange(start + before.length, end + before.length)
  }, 0)
}

const handleKeyDown = (e: KeyboardEvent) => {
  // Ctrl/Cmd + B pour gras
  if ((e.ctrlKey || e.metaKey) && e.key === 'b') {
    e.preventDefault()
    insertMarkdown('**', '**')
  }
  // Ctrl/Cmd + I pour italique
  if ((e.ctrlKey || e.metaKey) && e.key === 'i') {
    e.preventDefault()
    insertMarkdown('_', '_')
  }
  // Tab pour indentation
  if (e.key === 'Tab') {
    e.preventDefault()
    insertMarkdown('  ')
  }
}

defineExpose({
  focus: () => textareaRef.value?.focus(),
  blur: () => textareaRef.value?.blur(),
})
</script>
