// inertia/pages/departments/all.vue
<template>
  <Head title="Départements" />
  <section class="container max-w-4xl mx-auto my-40 space-y-10 px-5">
    <Typography variant="h1">Départements (ordre alphabétique)</Typography>
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <Link
        v-for="department in DEPARTMENTS.toSorted((a, b) =>
          a.shortTitle.localeCompare(b.shortTitle)
        )"
        :key="`department-${department.id}`"
        route="departments.single"
        :params="{ slug: department.slug }"
        as-child
      >
        <Card class="h-full bg-primary/10 card-hover cursor-pointer">
          <CardHeader>
            <CardTitle class="font-bold text-xl">{{ department.shortTitle }}</CardTitle>
            <CardContent class="text-sm mt-4 p-0">
              {{ department.description }}
            </CardContent>
          </CardHeader>
        </Card>
      </Link>
    </div>
  </section>
</template>
<script lang="ts" setup>
import { Typography } from '@/shared/components/ui/typography'
import { Card, CardContent, CardHeader, CardTitle } from '@/shared/components/ui/card'
import { DEPARTMENTS } from '@/shared/constants/departments.constants'
import Head from '@/shared/components/AppHead.vue'
import { Link } from '@adonisjs/inertia/vue'
</script>

// inertia/pages/services/all.tsx
import Head from '@/shared/components/app-head'
import { Link } from '@adonisjs/inertia/react'
import { ArrowRight, Heart } from 'lucide-react'
import { Card, CardContent, CardFooter } from '@/shared/components/ui/card'
import { cn } from '@/lib/utils'
import HeroSection from '@/shared/components/layout/default/hero-section'
import { CHURCH_SERVICES } from '@/features/church-services/constants/church_services.constants'

export default function ServicesPage() {
  return (
    <>
      <Head title="Services" />

      <HeroSection bgColor="bg-linear-to-r from-catholic-blue to-catholic-blue/90" py="16">
        <h1 className="text-4xl md:text-5xl font-bold mb-4 font-serif">Services</h1>
        <p className="text-xl opacity-90">
          Tous les sacrements et sacramentaux catholiques ainsi que les services proposés pour vivre
          sa foi en Église
        </p>
      </HeroSection>

      <section className="py-16">
        <div className="container max-w-7xl mx-auto px-4">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {CHURCH_SERVICES.map((service) => (
              <Link key={service.id} route="services.single" routeParams={{ slug: service.slug }}>
                <Card className="flex justify-between h-full bg-primary/10 card-hover text-center">
                  <CardContent className="p-6">
                    <div
                      className={cn(
                        'size-12 bg-catholic-gold text-white rounded-full flex items-center justify-center mx-auto mb-4',
                        service.iconClasses
                      )}
                    >
                      {service.icon ? (
                        <service.icon className="size-6" />
                      ) : (
                        <Heart className="size-6" />
                      )}
                    </div>
                    <h3 className="font-semibold mb-2">{service.title}</h3>
                    <p className="text-sm text-gray-600 text-justify mb-4">{service.description}</p>
                  </CardContent>
                  <CardFooter className="flex gap-2 justify-end text-right text-gray-600 font-medium">
                    Lire plus <ArrowRight className="size-4" />
                  </CardFooter>
                </Card>
              </Link>
            ))}
          </div>
        </div>
      </section>
    </>
  )
}
