// inertia/pages/dashboard/jobs/edit.tsx
import { InertiaProps } from '@/types'
import { editJobFormOpts } from '@/features/jobs/constants/form_opts'
import Head from '@/shared/components/app-head'
import { Button } from '@/shared/components/ui/button'
import { Link } from '@adonisjs/inertia/react'
import { ArrowLeft } from 'lucide-react'
import { JobDashboardForm } from '@/features/jobs/components/form/dashboard/job-dashboard-form'
import { useAppForm } from '@/shared/hooks/form'
import { hasRoute, urlFor } from '@/client'
import { router } from '@inertiajs/react'
import type { Data } from '@generated/data'
import { serverErrorsFormConvertor } from '@/lib/utils'

type PageProps = InertiaProps<{
  job: Data.Careers.JobPosting.Variants['allFields']
}>

export default function DashboardEditJobPostingPage({ job }: PageProps) {
  const form = useAppForm({
    ...editJobFormOpts(job),
    onSubmit: ({ value }) => {
      if (!hasRoute('dashboard.dashboard_jobs.update')) return
      router.put(
        urlFor('dashboard.dashboard_jobs.update', {
          id: job.id,
        }),
        value,
        {
          onError: (err) => {
            form.setErrorMap({
              onSubmit: serverErrorsFormConvertor(err),
            })
          },
        }
      )
    },
  })

  return (
    <>
      <Head title="Modifier l'offre d'emploi" />

      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" asChild>
            <Link route="dashboard.dashboard_jobs.index">
              <ArrowLeft className="h-4 w-4" />
            </Link>
          </Button>
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Modifier l'offre d'emploi</h1>
            <p className="text-gray-500 dark:text-gray-400">{job.title}</p>
          </div>
        </div>

        <form
          id="edit-job-form"
          onSubmit={(e) => {
            e.preventDefault()
            form.handleSubmit()
          }}
        >
          <JobDashboardForm id="edit-job-form" form={form} variant="edit" />
        </form>
      </div>
    </>
  )
}

// inertia/pages/dashboard/jobs/edit.vue
<template>
  <Head title="Modifier l'offre d'emploi" />

  <div class="space-y-6">
    <div class="flex items-center gap-4">
      <Button variant="ghost" size="icon" as-child>
        <Link :href="urlFor('dashboard.dashboard_jobs.index')">
          <ArrowLeft class="h-4 w-4" />
        </Link>
      </Button>
      <div>
        <h1 class="text-3xl font-bold tracking-tight">Modifier l'offre d'emploi</h1>
        <p class="text-gray-500 dark:text-gray-400">
          {{ job.title }}
        </p>
      </div>
    </div>

    <JobDashboardForm id="edit-job-form" :form="form" variant="edit" @submit="onSubmit" />
  </div>
</template>
<script lang="ts" setup>
import { Head, Link, router } from '@inertiajs/vue3'
import { Button } from '@/shared/components/ui/button'
import { ArrowLeft } from 'lucide-vue-next'
import { hasRoute, urlFor } from '@/client'
import JobDashboardForm from '@/features/jobs/components/form/dashboard/JobDashboardForm.vue'
import { useDashboardEditJobForm } from '@/features/jobs/composables/dashboard/use_dashboard_job_form'
import type { InertiaProps } from '@/types'
import type { Data } from '@generated/data'

type PageProps = InertiaProps<{
  job: Data.Careers.JobPosting.Variants['allFields']
}>

const props = defineProps<PageProps>()

const form = useDashboardEditJobForm(props.job)

const onSubmit = (values: Record<string, any>) => {
  if (!hasRoute('dashboard.dashboard_jobs.update')) return
  router.put(
    urlFor('dashboard.dashboard_jobs.update', {
      id: props.job.id,
    }),
    values,
    {
      onError: (res: Record<string, any>) => {
        form.setErrors(res)
      },
    }
  )
}
</script>
