// inertia/pages/decrees/single.tsx
import { InertiaProps } from '@/types'
import { Typography } from '@/shared/components/ui/typography'
import { Container } from '@/shared/components/ui/container'
import { MarkdownContent } from '@/shared/components/ui/markdown'
import { Button } from '@/shared/components/ui/button'
import { Link } from '@adonisjs/inertia/react'
import { ChevronLeft } from 'lucide-react'
import Head from '@/shared/components/app-head'
import { toOgDescription } from '@/lib/utils'
import { useMemo } from 'react'

type PageProps = InertiaProps<{
  title: string
  description: string
  timestamp?: string
  image?: string
  thumbnail?: string
  fields: Array<{ name: string; value: string }>
}>

export default function Single({ title, description, timestamp, image, fields }: PageProps) {
  const metaDescription = useMemo(() => toOgDescription(description), [description])

  return (
    <>
      <Head title={title}>
        <meta property="article:section" content="Décrets" />
        <meta head-key="og:type" property="og:type" content="article" />

        <meta head-key="og:description" property="og:description" content={metaDescription} />
        <meta
          head-key="twitter:description"
          property="twitter:description"
          content={metaDescription}
        />

        <meta head-key="twitter:card" name="twitter:card" content="summary_large_image" />
        {image && (
          <>
            <meta head-key="og:image" property="og:image" content={image} />
            <meta head-key="twitter:image" property="twitter:image" content={image} />
          </>
        )}

        {timestamp && <meta property="article:published_time" content={timestamp} />}
      </Head>
      <Container as="article" size="content" className="flex flex-col gap-5 py-50">
        <Link route="decrees.index" className="mb-5">
          <Button variant="link">
            <ChevronLeft /> Voir les autres décrets
          </Button>
        </Link>

        <Typography variant="h2">{title}</Typography>

        {image && (
          <img
            src={image}
            className="mx-auto py-5 max-w-1/3 h-auto"
            alt="Decree image (generally the seal of the archbishop or seal/logo of the decree's author)"
            loading="lazy"
          />
        )}

        {timestamp && (
          <Typography>
            Le <time>{new Date(timestamp).toLocaleDateString('fr-FR')}</time>,
          </Typography>
        )}

        <div>
          <MarkdownContent content={description} />
          {fields.length > 0 && (
            <Typography variant="list">
              {fields.map((field, i) => (
                <li key={i}>
                  <strong>{field.name}</strong> : <MarkdownContent content={field.value} />
                </li>
              ))}
            </Typography>
          )}
        </div>
      </Container>
    </>
  )
}

// inertia/pages/news/single.vue
<template>
  <Head
    :title="post.title"
    :description="post.excerpt || post.title"
    :image="post.coverImageUrl || undefined"
  >
    <meta head-key="og:type" property="og:type" content="article" />
    <meta head-key="twitter:card" name="twitter:card" content="summary_large_image" />

    <meta v-if="post.publishedAt" property="article:published_time" :content="post.publishedAt" />
    <meta v-if="post.updatedAt" property="article:modified_time" :content="post.updatedAt" />
    <meta property="article:section" :content="post.category" />
  </Head>
  <article>
    <header>
      <PageBanner :bg-image="post.coverImageUrl || undefined" py="16">
        <div class="flex flex-col gap-5">
          <Typography variant="h1" class="md:text-5xl font-bold mb-4">
            {{ post.title }}
          </Typography>
          <p class="text-xl opacity-90">
            {{ post.excerpt }}
          </p>
        </div>
      </PageBanner>
    </header>

    <div class="container mx-auto px-4 py-12 lg:py-16">
      <div class="max-w-4xl mx-auto">
        <div class="article-content">
          <div class="flex flex-col mb-10">
            <span class="font-bold uppercase">Pour diffusion immédiate</span>
            <time v-if="post.publishedAt" :datetime="post.publishedAt">{{
              formatDate(post.publishedAt)
            }}</time>
          </div>
          <MarkdownContent :content="post.content" class="prose text-justify" />
        </div>
      </div>
    </div>
  </article>
</template>

<script setup lang="ts">
import Head from '@/shared/components/AppHead.vue'
import PageBanner from '@/shared/components/layout/PageBanner.vue'
import { formatDate } from '@/lib/utils'
import { Typography } from '@/shared/components/ui/typography'
import { MarkdownContent } from '@/shared/components/ui/markdown'
import type { InertiaProps } from '@/types'
import type { Data } from '@generated/data'

type PageProps = InertiaProps<{
  post: Data.News.Variants['publicDetails']
}>

const { post } = defineProps<PageProps>()
</script>
<style scoped>
.article-content {
  line-height: 1.75;

  @media (max-width: 640px) {
    font-size: 1rem;
    line-height: 1.6;
  }
}

.article-content :deep(blockquote) {
  position: relative;
}

.article-content :deep(blockquote):before {
  content: '"';
  font-size: 4rem;
  color: var(--color-primary);
  opacity: 0.3;
  position: absolute;
  left: -0.5rem;
  top: -1rem;
}

.article-content :deep(a) {
  word-break: break-word;
}

.article-content :deep(ul li),
.article-content :deep(ol li) {
  margin-bottom: 0.5rem;
}

.article-content :deep(figure) {
  margin: 2rem 0;
}

.article-content :deep(figcaption) {
  text-align: center;
  font-style: italic;
  color: var(--color-gray-600);
  font-size: 0.875rem;
  margin-top: 0.5rem;
}
</style>
