// inertia/components/forms/money-input/MoneyInput.vue
<template>
  <FormField v-slot="{ value }" :name="name">
    <FormItem>
      <FormLabel v-if="props.label" class="text-sm font-medium text-gray-700 mb-3 block">
        {{ props.label }}
      </FormLabel>

      <div class="mt-1" v-if="showCustomField">
        <div class="flex justify-between">
          <NumberField
            :min="minAmount"
            :max="maxAmount"
            :format-options="currencyFormat"
            :model-value="value"
            class="w-full"
            @update:model-value="handleAmountChange"
          >
            <NumberFieldContent>
              <NumberFieldDecrement />
              <FormControl>
                <NumberFieldInput />
              </FormControl>
              <NumberFieldIncrement />
            </NumberFieldContent>
          </NumberField>
          <Button
            variant="ghost"
            class="px-2 cursor-pointer hover:bg-transparent"
            size="icon"
            @click="showCustomField = false"
          >
            <CircleX class="size-6 text-muted-foreground" />
          </Button>
        </div>
      </div>
      <div v-else class="grid gap-2 mb-4" :class="gridClass">
        <Button
          v-for="prefAmount in props.predefinedAmounts"
          :key="prefAmount"
          variant="outline"
          :class="cn({ [selectedClass]: prefAmount === value })"
          @click="() => setFieldValue('amount', prefAmount)"
        >
          {{ formatCurrency(prefAmount) }}
        </Button>
        <Button variant="outline" @click="showCustomField = true"> Autre </Button>
      </div>
      <FormMessage />
    </FormItem>
  </FormField>
</template>
<script setup lang="ts">
import {
  NumberField,
  NumberFieldContent,
  NumberFieldDecrement,
  NumberFieldIncrement,
  NumberFieldInput,
} from '@/components/ui/number-field'
import { CircleX } from 'lucide-vue-next'
import { FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form'
import { Button } from '@/components/ui/button'
import { computed, ref } from 'vue'
import { useFormContext } from 'vee-validate'
import { cn } from '@/lib/utils'

type Props = {
  name: string
  label?: string
  predefinedAmounts?: number[]
  minAmount?: number
  maxAmount?: number
  currency?: string
  locale?: string
  selectedClass?: string
  gridCols?: number
}

const props = withDefaults(defineProps<Props>(), {
  label: 'Montant',
  predefinedAmounts: () => [100000, 50000, 20000, 10000, 5000],
  minAmount: 0,
  maxAmount: undefined,
  currency: 'USD',
  locale: 'fr-FR',
  selectedClass: 'bg-blue-50 border-blue-500 text-blue-700',
  gridCols: 4,
})

const { setFieldValue } = useFormContext()

const showCustomField = ref<boolean>(false)

const currencyFormat = computed(
  (): Intl.NumberFormatOptions => ({
    style: 'currency',
    currency: props.currency,
    currencyDisplay: 'code',
    currencySign: 'accounting',
  })
)

const gridClass = computed(() => {
  const base = 'grid-cols-2 sm:grid-cols-'
  return base + props.gridCols
})

const formatCurrency = (amount: number) => {
  return new Intl.NumberFormat(props.locale, {
    style: 'currency',
    currency: props.currency,
    currencyDisplay: 'symbol',
    maximumSignificantDigits: 2,
  })
    .format(amount)
    .replace('US', '')
    .trim()
}

const handleAmountChange = (v: number | undefined) => {
  if (v) {
    setFieldValue(props.name, v)
  } else {
    setFieldValue(props.name, 0)
  }
}
</script>

// inertia/shared/components/fields/money-input.tsx
import { type ReactNode, useState } from 'react'
import { CircleX } from 'lucide-react'
import { Button } from '@/shared/components/ui/button'
import {
  NumberField,
  NumberFieldContent,
  NumberFieldDecrement,
  NumberFieldIncrement,
  NumberFieldInput,
} from '@/shared/components/ui/number-field'
import { Field, FieldDescription, FieldError, FieldLabel } from '@/shared/components/ui/field'
import { cn } from '@/lib/utils'

type Props = {
  name: string
  label?: string
  description?: ReactNode
  value?: number
  onChange?: (value: number) => void
  isInvalid?: boolean
  errors: Array<{ message?: string } | undefined>
  predefinedAmounts?: number[]
  minAmount?: number
  maxAmount?: number
  currency?: string
  locale?: string
  selectedClass?: string
  gridCols?: number
}

export default function AmountField({
  name,
  label = 'Montant',
  description,
  value,
  onChange,
  isInvalid = false,
  errors = [],
  predefinedAmounts = [100000, 50000, 20000, 10000, 5000],
  minAmount = 0,
  maxAmount,
  currency = 'USD',
  locale = 'fr-FR',
  selectedClass = 'bg-blue-50 border-blue-500 text-blue-700',
  gridCols = 4,
}: Props) {
  const [showCustomField, setShowCustomField] = useState(false)

  const gridClass = `grid grid-cols-2 sm:grid-cols-${gridCols} gap-2 mb-4`

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat(locale, {
      style: 'currency',
      currency,
      currencyDisplay: 'symbol',
      maximumSignificantDigits: 2,
    })
      .format(amount)
      .replace('US', '')
      .trim()
  }

  const handleAmountChange = (val: number | null) => {
    onChange?.(val ?? 0)
  }

  return (
    <Field data-invalid={isInvalid}>
      {label && (
        <FieldLabel htmlFor={name} className="text-sm font-medium text-gray-700 mb-3 block">
          {label}
        </FieldLabel>
      )}

      {showCustomField ? (
        <div className="mt-1">
          <div className="flex justify-between">
            <NumberField
              id={name}
              name={name}
              min={minAmount}
              max={maxAmount}
              formatOptions={{
                style: 'currency',
                currency: currency,
                currencyDisplay: 'code',
                currencySign: 'accounting',
              }}
              value={value}
              onChange={(val) => handleAmountChange(val)}
              aria-invalid={isInvalid}
              className="w-full"
            >
              <NumberFieldContent>
                <NumberFieldDecrement />
                <NumberFieldInput />
                <NumberFieldIncrement />
              </NumberFieldContent>
            </NumberField>
            <Button
              variant="ghost"
              className="px-2 cursor-pointer hover:bg-transparent"
              size="icon"
              type="button"
              onClick={() => setShowCustomField(false)}
            >
              <CircleX className="size-6 text-muted-foreground" />
            </Button>
          </div>
        </div>
      ) : (
        <div className={gridClass}>
          {predefinedAmounts.map((prefAmount) => (
            <Button
              key={prefAmount}
              type="button"
              variant="outline"
              className={cn(prefAmount === value && selectedClass)}
              onClick={() => onChange?.(prefAmount)}
            >
              {formatCurrency(prefAmount)}
            </Button>
          ))}
          <Button type="button" variant="outline" onClick={() => setShowCustomField(true)}>
            Autre
          </Button>
        </div>
      )}

      {description && <FieldDescription>{description}</FieldDescription>}

      {isInvalid && <FieldError errors={errors} />}
    </Field>
  )
}
