// inertia/shared/components/map/gta5-map.tsx
import 'leaflet/dist/leaflet.css'
import type { LatLngExpression } from 'leaflet'
import { cn } from '@/lib/utils'
import {
  forwardRef,
  HTMLAttributes,
  PropsWithChildren,
  RefObject,
  useImperativeHandle,
  useRef,
} from 'react'
import { LayersControl, MapContainer } from 'react-leaflet'
import { CustomCRS } from '@/shared/components/map/custom_crs'
import { TileLayerWrapper } from '@/shared/components/map/title-layer-wrapper'
import type { MapRef } from 'react-leaflet/MapContainer'

type Props = PropsWithChildren<{
  ref?: RefObject<MapRef>
  center?: LatLngExpression
  zoom?: number
  className?: HTMLAttributes<HTMLElement>['className']
}>

export interface GTA5MapHandle {
  flyTo: (coords: LatLngExpression, flyZoom?: number, flyDuration?: number) => void
}

const commonOptions = {
  keepBuffer: 64,
  minZoom: 0,
  maxZoom: 5,
  noWrap: true,
}

export const GTA5Map = forwardRef(
  ({ children, center = [0, 0], zoom = 3, className }: Props, ref) => {
    const mapInstanceRef = useRef<MapRef>(null)

    useImperativeHandle(ref, () => ({
      flyTo: (coords: LatLngExpression, flyZoom: number = 5, flyDuration: number = 1.2) => {
        mapInstanceRef.current?.flyTo(coords, flyZoom, {
          animate: true,
          duration: flyDuration,
        })
      },
    }))

    return (
      <div className={cn('w-full h-screen relative', className)}>
        <MapContainer
          ref={mapInstanceRef}
          crs={CustomCRS()}
          minZoom={1}
          maxZoom={5}
          center={center}
          zoom={zoom}
          className="h-full w-full bg-inherit"
          preferCanvas
          attributionControl
        >
          <LayersControl position="topright">
            <LayersControl.BaseLayer name="Atlas">
              <TileLayerWrapper
                url="/map/assets/map-tiles/atlas/{z}/{x}/{y}.jpg"
                {...commonOptions}
              />
            </LayersControl.BaseLayer>

            <LayersControl.BaseLayer name="Satellite" checked>
              <TileLayerWrapper
                url="/map/assets/map-tiles/satelite/{z}/{x}/{y}.jpg"
                {...commonOptions}
              />
            </LayersControl.BaseLayer>
          </LayersControl>

          {children}
        </MapContainer>
      </div>
    )
  }
)

export default GTA5Map

// inertia/shared/components/map/GTA5Map.vue
<template>
  <div :class="cn('w-full h-screen relative', $attrs.class as string)">
    <div ref="mapContainer" class="h-full w-full bg-inherit"></div>
    <slot v-if="mapInstance" />
  </div>
</template>
<script setup lang="ts">
import { cn } from '@/lib/utils'
import type { LatLngExpression, LatLngTuple, Map } from 'leaflet'
import L from 'leaflet'
import { onBeforeUnmount, onMounted, provide, ref, shallowRef } from 'vue'
import 'leaflet/dist/leaflet.css'
import { CustomCRS } from '@/shared/components/map/custom_crs'

defineOptions({
  inheritAttrs: false,
})

const props = withDefaults(
  defineProps<{
    center?: LatLngExpression
    zoom?: number
  }>(),
  {
    center: () => [0, 0] as LatLngTuple,
    zoom: 3,
  }
)

const mapContainer = ref<HTMLElement | null>(null)
const mapInstance = shallowRef<Map | null>(null)

const flyTo = (coords: LatLngExpression, zoom?: number) => {
  if (mapInstance.value) {
    mapInstance.value.flyTo(coords, zoom || 5, {
      duration: 1.5,
      easeLinearity: 0.25,
    })
  }
}

provide('mapInstance', mapInstance)

defineExpose({ flyTo })

onMounted(() => {
  if (!mapContainer.value) return

  const map = L.map(mapContainer.value, {
    crs: CustomCRS,
    minZoom: 3,
    maxZoom: 5,
    preferCanvas: true,
    center: props.center,
    zoom: props.zoom,
    attributionControl: false,
  })

  const commonOptions = {
    keepBuffer: 64,
    noWrap: true,
    minZoom: 0,
    maxZoom: 5,
  }

  const atlas = L.tileLayer('/map/assets/map-tiles/atlas/{z}/{x}/{y}.jpg', commonOptions)
  const satellite = L.tileLayer('/map/assets/map-tiles/satelite/{z}/{x}/{y}.jpg', commonOptions)

  const baseMaps = {
    Atlas: atlas,
    Satellite: satellite,
  }

  L.control.layers(baseMaps, {}, { position: 'topright' }).addTo(map)

  satellite.addTo(map)

  mapInstance.value = map
})

onBeforeUnmount(() => {
  if (mapInstance.value) {
    mapInstance.value.remove()
  }
})
</script>
