// inertia/pages/dashboard/events/create.vue
<template>
  <DashboardLayout>
    <Head title="Créer un événement" />

    <div class="space-y-6">
      <div class="flex items-center gap-4">
        <Button variant="ghost" size="icon" as-child>
          <Link :href="tuyau.$url('dashboard.dashboard_events.index')">
            <ArrowLeft class="h-4 w-4" />
          </Link>
        </Button>
        <div>
          <h1 class="text-3xl font-bold tracking-tight">Créer un événement</h1>
          <p class="text-gray-500 dark:text-gray-400">
            Organisez un nouvel événement pour votre communauté
          </p>
        </div>
      </div>

      <form @submit.prevent="submit">
        <div class="grid gap-6 lg:grid-cols-3">
          <div class="lg:col-span-2 space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Informations principales</CardTitle>
                <CardDescription> Détails de base de l'événement </CardDescription>
              </CardHeader>
              <CardContent class="space-y-4">
                <div class="space-y-2">
                  <Label for="title">Titre *</Label>
                  <Input
                    id="title"
                    v-model="form.title"
                    placeholder="Titre de l'événement"
                    required
                    @blur="!form.slug && generateSlug()"
                  />
                  <p v-if="form.errors.title" class="text-sm text-red-600">
                    {{ form.errors.title }}
                  </p>
                </div>

                <div class="space-y-2">
                  <Label for="slug">Slug</Label>
                  <Input id="slug" v-model="form.slug" placeholder="url-de-levenement" />
                  <p class="text-xs text-gray-500">Laissez vide pour générer automatiquement</p>
                  <p v-if="form.errors.slug" class="text-sm text-red-600">
                    {{ form.errors.slug }}
                  </p>
                </div>

                <div class="space-y-2">
                  <Label for="description">Description *</Label>
                  <Textarea
                    id="description"
                    v-model="form.description"
                    placeholder="Résumé de l'événement"
                    :rows="3"
                    required
                  />
                  <p v-if="form.errors.description" class="text-sm text-red-600">
                    {{ form.errors.description }}
                  </p>
                </div>

                <div class="space-y-2">
                  <Label for="parishId">Paroisse</Label>
                  <Select
                    :value="form.parishId"
                    @update:model-value="
                      (value) => {
                        if (value === 'null') {
                          form.parishId = undefined
                          return
                        }
                        form.parishId = Number(value)
                      }
                    "
                  >
                    <SelectTrigger>
                      <SelectValue id="parishId" placeholder="Aucune" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectGroup>
                        <SelectItem value="null"> Aucune </SelectItem>
                        <SelectItem v-for="parish of parishes" :key="parish.id" :value="parish.id">
                          {{ parish.name }}
                        </SelectItem>
                      </SelectGroup>
                    </SelectContent>
                  </Select>
                  <p v-if="form.errors.parishId" class="text-sm text-red-600">
                    {{ form.errors.parishId }}
                  </p>
                </div>

                <div class="space-y-2">
                  <Label for="location">Lieu</Label>
                  <Input
                    id="location"
                    v-model="form.location"
                    placeholder="Adresse ou lieu de l'événement"
                  />
                  <p v-if="form.errors.location" class="text-sm text-red-600">
                    {{ form.errors.location }}
                  </p>
                </div>

                <div class="space-y-2">
                  <Label for="content">Contenu *</Label>
                  <MarkdownTextarea
                    id="content"
                    v-model="form.content"
                    placeholder="Description de l'événement"
                    :rows="12"
                    required
                  />
                  <p v-if="form.errors.content" class="text-sm text-red-600">
                    {{ form.errors.content }}
                  </p>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Dates et horaires</CardTitle>
              </CardHeader>
              <CardContent class="space-y-4">
                <div class="grid gap-4 md:grid-cols-2">
                  <div class="space-y-2">
                    <Label for="startDate">Date de début *</Label>
                    <Input id="startDate" v-model="form.startDate" type="datetime-local" required />
                    <p v-if="form.errors.startDate" class="text-sm text-red-600">
                      {{ form.errors.startDate }}
                    </p>
                  </div>

                  <div class="space-y-2">
                    <Label for="endDate">Date de fin</Label>
                    <Input id="endDate" v-model="form.endDate" type="datetime-local" />
                    <p v-if="form.errors.endDate" class="text-sm text-red-600">
                      {{ form.errors.endDate }}
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          <div class="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Publication</CardTitle>
              </CardHeader>
              <CardContent class="space-y-4">
                <div class="flex gap-2 items-center">
                  <Checkbox id="registrationRequired" v-model="form.registrationRequired" />
                  <Label for="registrationRequired">Inscription requise</Label>
                </div>
                <div v-if="form.registrationRequired" class="space-y-2">
                  <Label for="maxParticipants">Nombre max de participants</Label>
                  <Input
                    id="maxParticipants"
                    v-model.number="form.maxParticipants"
                    type="number"
                    min="1"
                    placeholder="Illimité si vide"
                  />
                  <p class="text-xs text-gray-500">Laissez vide pour un nombre illimité</p>
                </div>

                <div class="flex gap-2">
                  <Button type="submit" :disabled="form.processing" class="flex-1">
                    Créer l'événement
                  </Button>
                  <Button type="button" variant="outline" as-child>
                    <Link :href="tuyau.$url('dashboard.dashboard_events.index')"> Annuler </Link>
                  </Button>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Image de couverture</CardTitle>
              </CardHeader>
              <CardContent class="space-y-2">
                <Input
                  id="coverImage"
                  v-model="form.coverImageUrl"
                  placeholder="URL de l'image"
                  type="url"
                />
                <div
                  v-if="form.coverImageUrl"
                  class="mt-4 aspect-video w-full overflow-hidden rounded-lg border"
                >
                  <img :src="form.coverImageUrl" alt="Aperçu" class="h-full w-full object-cover" />
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Flyer</CardTitle>
              </CardHeader>
              <CardContent class="space-y-2">
                <Input
                  id="coverImage"
                  v-model="form.flyerUrl"
                  placeholder="URL de l'image"
                  type="url"
                />
                <div
                  v-if="form.flyerUrl"
                  class="mt-4 aspect-video w-full overflow-hidden rounded-lg border"
                >
                  <img :src="form.flyerUrl" alt="Aperçu" class="h-full w-full object-cover" />
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </form>
    </div>
  </DashboardLayout>
</template>

<script setup lang="ts">
import { Head, Link, useForm } from '@inertiajs/vue3'
import DashboardLayout from '@/layouts/DashboardLayout.vue'
import { Button } from '@/shared/components/ui/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/shared/components/ui/card'
import { Input } from '@/shared/components/ui/input'
import { Label } from '@/shared/components/ui/label'
import { Textarea } from '@/shared/components/ui/textarea'
import { ArrowLeft } from 'lucide-vue-next'
import { tuyau } from '@/lib/tuyau'
import { MarkdownTextarea } from '@/shared/components/ui/markdown'
import { parishes } from '@/shared/constants/parishes.constants'
import { Checkbox } from '@/shared/components/ui/checkbox'
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/shared/components/ui/select'

const form = useForm({
  title: '',
  slug: '',
  description: '',
  content: '',
  location: '',
  parishId: undefined as number | undefined,
  coverImageUrl: '',
  flyerUrl: '',
  registrationRequired: false,
  maxParticipants: undefined as number | undefined,
  startDate: '',
  endDate: '',
})

const submit = () => {
  form.post(tuyau.$url('dashboard.dashboard_events.store'))
}

const generateSlug = () => {
  form.slug = form.title
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}
</script>

// src/routes/dashboard/events/create.tsx
import { useQueryClient } from '@tanstack/react-query'
import { createFileRoute, Link } from '@tanstack/react-router'
import { toast } from 'sonner'
import { parishes } from '#/config/parishes.ts'
import type {
  CreateChurchEventFormInput,
} from '#/features/church-event/schemas/church-event.schema.ts'
import { createChurchEventSchema } from '#/features/church-event/schemas/church-event.schema.ts'
import { DashboardHeading } from '#/features/dashboard/components/dashboard-heading.tsx'
import { createChurchEventFn } from '#/server-fn/church-event.functions.ts'
import { pageMetadata } from '#/utils/seo.ts'
import { buttonVariants } from '#shared/components/ui/button.tsx'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '#shared/components/ui/card.tsx'
import { Field, FieldError, FieldGroup } from '#shared/components/ui/field.tsx'
import { Input } from '#shared/components/ui/input.tsx'
import { Separator } from '#shared/components/ui/separator.tsx'
import { useAppForm } from '#shared/integrations/form/form-hook.ts'

export const Route = createFileRoute('/dashboard/events/create')({
  head: () => ({ meta: pageMetadata('Créer un événement') }),
  component: RouteComponent,
})

function RouteComponent() {
  const queryClient = useQueryClient()
  const navigate = Route.useNavigate()

  const form = useAppForm({
    validators: {
      onChangeAsync: createChurchEventSchema,
    },
    defaultValues: {
      parish: null,
      flyerUrl: null,
      registrationRequired: false,
      maxParticipants: null,
      endDate: null,
    } as CreateChurchEventFormInput,
    onSubmit: async ({ value, formApi }) => {
      const result = await createChurchEventFn({ data: value })

      if (!result.success) {
        if (result.validationErrors) {
          return formApi.setErrorMap({
            onServer: {
              fields: result.validationErrors,
            },
          } as unknown as Parameters<typeof formApi.setErrorMap>[0])
        }

        return toast.error(result.error)
      }

      await queryClient.invalidateQueries({ queryKey: ['events'] })

      void navigate({ to: '/dashboard/events/show/$id', params: { id: result.churchEventId } })
      toast.success('Événement créé !')
    },
  })

  return (
    <div className="container mx-auto pt-5">
      <div className="space-y-6">
        <DashboardHeading
          title="Créer un événement"
          description="Publier un nouvel événement de l'archidiocèse sur l'application"
          backButton={{
            'to': '/dashboard/events',
            'aria-label': "Retour sur la page d'administration des événements",
            'preload': false,
          }}
        />
        <div className="grid gap-6 lg:grid-cols-3">
          <form.AppForm>
            <form
              id="create-church-event-form"
              onSubmit={(e) => {
                e.preventDefault()
                void form.handleSubmit()
              }}
              className="contents"
            >
              <div className="space-y-6 lg:col-span-2">
                <Card>
                  <CardHeader>
                    <CardTitle>Informations principales</CardTitle>
                    <CardDescription>Modifiez les détails de l'événement</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <FieldGroup>
                      <form.AppField name="title">
                        {(field) => (
                          <field.InputField
                            label="Titre"
                            placeholder="Titre de l'événement"
                            required
                          />
                        )}
                      </form.AppField>

                      <form.AppField name="slug">
                        {(field) => (
                          <field.InputField
                            label="Slug"
                            description="Laissez vide pour générer automatiquement"
                            placeholder="url-de-levenement"
                          />
                        )}
                      </form.AppField>

                      <form.AppField name="description">
                        {(field) => (
                          <field.TextareaField
                            label="Description"
                            placeholder="Description de l'événement"
                            rows={3}
                            required
                          />
                        )}
                      </form.AppField>

                      <form.AppField name="parish">
                        {(field) => (
                          <field.SelectField
                            label="Paroisse"
                            errorsPos="after"
                            values={[
                              { label: 'Sélectionner une paroisse', value: null },
                              ...parishes.map((parish) => ({
                                label: parish.title,
                                value: parish.id,
                              })),
                            ]}
                          />
                        )}
                      </form.AppField>

                      <form.AppField name="location">
                        {(field) => (
                          <field.InputField
                            label="Lieu"
                            placeholder="Adresse ou lieu de l'événement"
                            required
                          />
                        )}
                      </form.AppField>

                      <form.AppField name="content">
                        {(field) => (
                          <field.TextareaField
                            label="Contenu"
                            placeholder="Plus de détails sur l'événement..."
                            rows={12}
                            markdown
                            required
                          />
                        )}
                      </form.AppField>
                    </FieldGroup>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle>Dates et horaires</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="grid gap-4 md:grid-cols-2">
                      <form.AppField
                        name="startDate"
                        validators={{
                          onChangeListenTo: ['endDate'],
                        }}
                      >
                        {(field) => <field.DateTimePickerField label="Date de début" required />}
                      </form.AppField>

                      <form.AppField
                        name="endDate"
                        validators={{
                          onChangeListenTo: ['startDate'],
                          onChange: ({ value, fieldApi }) => {
                            const startDate = fieldApi.form.getFieldValue('startDate')

                            // oxlint-disable-next-line typescript/no-unnecessary-condition
                            if (value && startDate && value <= startDate) {
                              return { message: 'La date de fin doit être après la date de début.' }
                            }
                            return undefined
                          },
                        }}
                      >
                        {(field) => <field.DateTimePickerField label="Date de fin" />}
                      </form.AppField>
                    </div>
                  </CardContent>
                </Card>
              </div>

              <div className="space-y-6">
                <Card>
                  <CardHeader>
                    <CardTitle>Publication</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <FieldGroup>
                      <form.AppField name="registrationRequired">
                        {(field) => (
                          <field.CheckboxField
                            label="Inscription requise"
                            fieldProps={{ orientation: 'horizontal' }}
                          />
                        )}
                      </form.AppField>
                      <form.Subscribe selector={(state) => state.values.registrationRequired}>
                        {(isRegistrationRequired) => {
                          if (!isRegistrationRequired) return null

                          return (
                            <form.AppField name="maxParticipants">
                              {(field) => (
                                <field.InputField
                                  type="number"
                                  label="Nombre max. de participants"
                                  placeholder="Illimité"
                                  description="Laissez vide pour un nombre illimité"
                                />
                              )}
                            </form.AppField>
                          )
                        }}
                      </form.Subscribe>
                    </FieldGroup>

                    <Separator />

                    <Field orientation="horizontal">
                      <form.SubmitButton
                        label="Créer l'événement"
                        submittingLabel="Création..."
                        form="create-church-event-form"
                        disabled={(state) => !state.canSubmit || !state.isDirty}
                        className="flex-1"
                      />

                      <Link
                        type="button"
                        to="/dashboard/events"
                        className={buttonVariants({ variant: 'outline' })}
                      >
                        Annuler
                      </Link>
                    </Field>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle>Image de couverture *</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <form.AppField name="coverImageUrl">
                      {(field) => {
                        const isInvalid = field.state.meta.isTouched && !field.state.meta.isValid
                        return (
                          <Field data-invalid={isInvalid}>
                            <Input
                              id={field.name}
                              name={field.name}
                              value={field.state.value}
                              onBlur={field.handleBlur}
                              onChange={(e) => field.handleChange(e.target.value)}
                              aria-invalid={isInvalid}
                              placeholder="URL de l'image"
                              type="url"
                              required
                            />
                            {isInvalid && <FieldError errors={field.state.meta.errors} />}
                            {field.state.value && !isInvalid && (
                              <div className="mt-4 aspect-video w-full overflow-hidden rounded-lg border">
                                <img
                                  src={field.state.value}
                                  alt="Aperçu"
                                  className="h-full w-full object-cover"
                                />
                              </div>
                            )}
                          </Field>
                        )
                      }}
                    </form.AppField>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle>Affiche / Flyer</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <form.AppField name="flyerUrl">
                      {(field) => {
                        const isInvalid = field.state.meta.isTouched && !field.state.meta.isValid
                        return (
                          <Field data-invalid={isInvalid}>
                            <Input
                              id={field.name}
                              name={field.name}
                              value={field.state.value ?? ''}
                              onBlur={field.handleBlur}
                              onChange={(e) => field.handleChange(e.target.value)}
                              aria-invalid={isInvalid}
                              placeholder="URL de l'image"
                              type="url"
                            />
                            {isInvalid && <FieldError errors={field.state.meta.errors} />}
                            {field.state.value && !isInvalid && (
                              <div className="mt-4 aspect-video w-full overflow-hidden rounded-lg border">
                                <img
                                  src={field.state.value}
                                  alt="Aperçu"
                                  className="h-full w-full object-cover"
                                />
                              </div>
                            )}
                          </Field>
                        )
                      }}
                    </form.AppField>
                  </CardContent>
                </Card>
              </div>
            </form>
          </form.AppForm>
        </div>
      </div>
    </div>
  )
}
