// inertia/features/contact/components/form/ContactForm.vue
<template>
  <form @submit="submitForm" class="space-y-6">
    <div class="grid md:grid-cols-2 gap-4">
      <div
        v-for="item of [
          { id: 'firstname', label: 'Prénom', placeholder: 'John' },
          { id: 'lastname', label: 'Nom de famille', placeholder: 'Doe' },
        ]"
        :key="item.id"
      >
        <VeeField v-slot="{ componentField, errors: fieldErrors }" :name="item.id">
          <Field :data-invalid="!!fieldErrors.length">
            <FieldLabel :for="item.id" class="block text-sm font-medium text-gray-700">
              {{ item.label }} *
            </FieldLabel>
            <Input
              :id="item.id"
              v-bind="componentField"
              type="text"
              :placeholder="item.placeholder"
              :aria-invalid="!!fieldErrors.length"
              class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-catholic-gold focus:border-transparent"
            />
            <FieldError v-if="fieldErrors.length" :errors="fieldErrors" />
          </Field>
        </VeeField>
      </div>
    </div>

    <div>
      <VeeField v-slot="{ field, errors: fieldErrors }" name="phone">
        <Field :data-invalid="!!fieldErrors.length">
          <FieldLabel :for="field.name" class="block text-sm font-medium text-gray-700">
            Téléphone *
          </FieldLabel>
          <Input
            :id="field.name"
            v-bind="field"
            type="tel"
            placeholder="1234"
            :aria-invalid="!!fieldErrors.length"
            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-catholic-gold focus:border-transparent"
          />
          <FieldError v-if="fieldErrors.length" :errors="fieldErrors" />
        </Field>
      </VeeField>
    </div>

    <div>
      <VeeField v-slot="{ field, errors: fieldErrors }" name="subject">
        <Field :data-invalid="!!fieldErrors.length">
          <FieldLabel :for="field.name" class="block text-sm font-medium text-gray-700 mb-1">
            Sujet *
          </FieldLabel>
          <Select
            :model-value="field.value"
            @update:model-value="field.onChange"
            @blur="field.onBlur"
          >
            <SelectTrigger
              :id="field.name"
              class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-catholic-gold focus:border-transparent"
              :aria-invalid="!!fieldErrors.length"
            >
              <SelectValue placeholder="Choisissez un sujet" />
            </SelectTrigger>
            <SelectContent>
              <SelectGroup>
                <SelectItem v-for="item in props.subjects" :key="item.id" :value="item.id">
                  {{ item.label }}
                </SelectItem>
              </SelectGroup>
            </SelectContent>
          </Select>
          <FieldError v-if="fieldErrors.length" :errors="fieldErrors" />
        </Field>
      </VeeField>
    </div>

    <div>
      <VeeField v-slot="{ field, errors: fieldErrors }" name="message">
        <Field :data-invalid="!!fieldErrors.length">
          <FieldLabel :for="field.name" class="block text-sm font-medium text-gray-700 mb-1">
            Message *
          </FieldLabel>
          <Textarea
            :id="field.name"
            v-bind="field"
            :rows="6"
            :maxlength="2000"
            placeholder="Décrivez votre demande en détail..."
            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-catholic-gold focus:border-transparent"
            :aria-invalid="!!fieldErrors.length"
          />
          <FieldError v-if="fieldErrors.length" :errors="fieldErrors" />
        </Field>
      </VeeField>
    </div>

    <Button
      type="submit"
      size="lg"
      class="w-full bg-catholic-gold hover:bg-yellow-600 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed"
      :disabled="isSubmitting"
    >
      <component
        :is="isSubmitting ? Loader2 : Send"
        :class="['size-5 mr-2', isSubmitting && 'animate-spin']"
      />
      {{ isSubmitting ? 'Envoi en cours...' : 'Envoyer le message' }}
    </Button>

    <p class="text-sm text-gray-500">* Champs obligatoires</p>
  </form>
</template>
<script setup lang="ts">
import { Loader2, Send } from 'lucide-vue-next'
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/shared/components/ui/select'
import { Button } from '@/shared/components/ui/button'
import { Textarea } from '@/shared/components/ui/textarea'
import { Input } from '@/shared/components/ui/input'
import { Field as VeeField, useForm } from 'vee-validate'
import { watch } from 'vue'
import { router } from '@inertiajs/vue3'
import { urlFor } from '@/client'
import { toast } from 'vue-sonner'
import { useCurrentCharacter } from '@/shared/composables/use_current_character'
import { useErrors } from '@/shared/composables/use_errors'
import { toTypedSchema } from '@vee-validate/zod'
import { contactSchema } from '@/features/contact/schemas/contact.schema'
import { Field, FieldError, FieldLabel } from '@/shared/components/ui/field'
import type { CONTACT_SUBJECTS } from '#shared/constants/contact_subjects'
import { usePageProps } from '@/shared/composables/use_page_props'

type PageProps = {
  subjects: typeof CONTACT_SUBJECTS
}

const props = usePageProps<PageProps>()
const errors = useErrors()

const currentCharacter = useCurrentCharacter()

const { handleSubmit, isSubmitting, setErrors, resetForm } = useForm({
  validationSchema: toTypedSchema(contactSchema),
  initialValues: {
    firstname: currentCharacter.value?.firstname || '',
    lastname: currentCharacter.value?.lastname || '',
    phone: '',
    subject: undefined,
    message: '',
  },
})

watch(
  () => errors.value,
  (newErrors: Record<string, string | string[]>) => {
    if (newErrors && Object.keys(newErrors).length > 0) {
      setErrors(newErrors)
    }
  },
  { immediate: true }
)

const submitForm = handleSubmit((values) => {
  router.post(urlFor('contact.submit'), values, {
    preserveScroll: true,
    onSuccess: () => {
      if (props.value.success) {
        resetForm()
        return toast.success(props.value.success || 'Submitted!')
      }
    },
    onError: (err) => {
      setErrors(err)
    },
  })
})
</script>

// inertia/features/contact/components/form/contact-form.tsx
import { Loader2, Send } from 'lucide-react'
import { router, usePage } from '@inertiajs/react'
import { useForm } from '@tanstack/react-form'
import { toast } from 'sonner'
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/shared/components/ui/select'
import { Button } from '@/shared/components/ui/button'
import { Textarea } from '@/shared/components/ui/textarea'
import { Input } from '@/shared/components/ui/input'
import { Field, FieldError, FieldGroup, FieldLabel } from '@/shared/components/ui/field'
import { contactSchema } from '@/features/contact/schemas/contact.schema'
import { useCurrentCharacter } from '@/shared/hooks/use_current_character'
import type { CONTACT_SUBJECTS } from '#shared/constants/contact_subjects'
import { urlFor } from '@/client'
import { serverErrorsFormConvertor } from '@/lib/utils'

type Props = {
  subjects: typeof CONTACT_SUBJECTS
}

export default function ContactForm() {
  const { subjects } = usePage<Props>().props
  const currentCharacter = useCurrentCharacter()

  const form = useForm({
    validators: { onSubmit: contactSchema },
    defaultValues: {
      firstname: currentCharacter?.firstname ?? '',
      lastname: currentCharacter?.lastname ?? '',
      phone: '',
      subject: '',
      message: '',
    },
    onSubmit: ({ value }) => {
      router.post(urlFor('contact.submit'), value, {
        preserveScroll: true,
        onSuccess: () => {
          form.reset()
          toast.success('Message envoyé !')
        },
        onError: (err) => {
          form.setErrorMap({ onSubmit: serverErrorsFormConvertor(err) })
        },
      })
    },
  })

  return (
    <form
      className="space-y-6"
      onSubmit={(e) => {
        e.preventDefault()
        form.handleSubmit()
      }}
    >
      <FieldGroup>
        <div key={currentCharacter?.id} className="grid md:grid-cols-2 gap-4">
          {(
            [
              { name: 'firstname', label: 'Prénom', placeholder: 'John' },
              { name: 'lastname', label: 'Nom de famille', placeholder: 'Doe' },
            ] as const
          ).map((item) => (
            <form.Field
              key={item.name}
              name={item.name}
              children={(field) => {
                const isInvalid = field.state.meta.isTouched && !field.state.meta.isValid
                return (
                  <Field data-invalid={isInvalid}>
                    <FieldLabel
                      htmlFor={field.name}
                      className="block text-sm font-medium text-gray-700"
                    >
                      {item.label} *
                    </FieldLabel>
                    <Input
                      id={field.name}
                      name={field.name}
                      value={field.state.value}
                      onBlur={field.handleBlur}
                      onChange={(e) => field.handleChange(e.target.value)}
                      type="text"
                      placeholder={item.placeholder}
                      aria-invalid={isInvalid}
                    />
                    {isInvalid && <FieldError errors={field.state.meta.errors} />}
                  </Field>
                )
              }}
            />
          ))}
        </div>

        <form.Field
          name="phone"
          children={(field) => {
            const isInvalid = field.state.meta.isTouched && !field.state.meta.isValid
            return (
              <Field data-invalid={isInvalid}>
                <FieldLabel
                  htmlFor={field.name}
                  className="block text-sm font-medium text-gray-700"
                >
                  Téléphone *
                </FieldLabel>
                <Input
                  id={field.name}
                  name={field.name}
                  value={field.state.value}
                  onBlur={field.handleBlur}
                  onChange={(e) => field.handleChange(e.target.value)}
                  type="tel"
                  placeholder="1234"
                  aria-invalid={isInvalid}
                />
                {isInvalid && <FieldError errors={field.state.meta.errors} />}
              </Field>
            )
          }}
        />

        <form.Field
          name="subject"
          children={(field) => {
            const isInvalid = field.state.meta.isTouched && !field.state.meta.isValid
            return (
              <Field data-invalid={isInvalid}>
                <FieldLabel
                  htmlFor={field.name}
                  className="block text-sm font-medium text-gray-700"
                >
                  Sujet *
                </FieldLabel>
                <Select
                  name={field.name}
                  value={field.state.value}
                  onValueChange={field.handleChange}
                >
                  <SelectTrigger id={field.name} aria-invalid={isInvalid}>
                    <SelectValue placeholder="Choisissez un sujet" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectGroup>
                      {subjects.map((item) => (
                        <SelectItem key={item.id} value={item.id}>
                          {item.label}
                        </SelectItem>
                      ))}
                    </SelectGroup>
                  </SelectContent>
                </Select>
                {isInvalid && <FieldError errors={field.state.meta.errors} />}
              </Field>
            )
          }}
        />

        <form.Field
          name="message"
          children={(field) => {
            const isInvalid = field.state.meta.isTouched && !field.state.meta.isValid
            return (
              <Field data-invalid={isInvalid}>
                <FieldLabel
                  htmlFor={field.name}
                  className="block text-sm font-medium text-gray-700"
                >
                  Message *
                </FieldLabel>
                <Textarea
                  id={field.name}
                  name={field.name}
                  value={field.state.value}
                  onBlur={field.handleBlur}
                  onChange={(e) => field.handleChange(e.target.value)}
                  rows={6}
                  maxLength={2000}
                  placeholder="Décrivez votre demande en détail..."
                  aria-invalid={isInvalid}
                />
                {isInvalid && <FieldError errors={field.state.meta.errors} />}
              </Field>
            )
          }}
        />
      </FieldGroup>

      <form.Subscribe
        selector={(state) => state.isSubmitting}
        children={(isSubmitting) => (
          <Button
            type="submit"
            size="lg"
            className="w-full bg-catholic-gold hover:bg-yellow-600 transition-all duration-200"
            disabled={isSubmitting}
          >
            {isSubmitting ? (
              <>
                <Loader2 className="size-5 mr-2 animate-spin" /> Envoi en cours...
              </>
            ) : (
              <>
                <Send className="size-5 mr-2" /> Envoyer le message
              </>
            )}
          </Button>
        )}
      />

      <p className="text-sm text-gray-500">* Champs obligatoires</p>
    </form>
  )
}
