// inertia/shared/components/map/GTA5Map.vue
<template>
  <div :class="cn('w-full h-screen relative', $attrs.class as string)">
    <div ref="mapContainer" class="h-full w-full bg-inherit"></div>
    <slot v-if="mapInstance" />
  </div>
</template>
<script setup lang="ts">
import { cn } from '@/lib/utils'
import type { LatLngExpression, LatLngTuple, Map } from 'leaflet'
import L from 'leaflet'
import { onBeforeUnmount, onMounted, provide, ref, shallowRef } from 'vue'
import 'leaflet/dist/leaflet.css'
import { CustomCRS } from '@/shared/components/map/custom_crs'

defineOptions({
  inheritAttrs: false,
})

const props = withDefaults(
  defineProps<{
    center?: LatLngExpression
    zoom?: number
  }>(),
  {
    center: () => [0, 0] as LatLngTuple,
    zoom: 3,
  }
)

const mapContainer = ref<HTMLElement | null>(null)
const mapInstance = shallowRef<Map | null>(null)

const flyTo = (coords: LatLngExpression, zoom?: number) => {
  if (mapInstance.value) {
    mapInstance.value.flyTo(coords, zoom || 5, {
      duration: 1.5,
      easeLinearity: 0.25,
    })
  }
}

provide('mapInstance', mapInstance)

defineExpose({ flyTo })

onMounted(() => {
  if (!mapContainer.value) return

  const map = L.map(mapContainer.value, {
    crs: CustomCRS,
    minZoom: 3,
    maxZoom: 5,
    preferCanvas: true,
    center: props.center,
    zoom: props.zoom,
    attributionControl: false,
  })

  const commonOptions = {
    keepBuffer: 64,
    noWrap: true,
    minZoom: 0,
    maxZoom: 5,
  }

  const atlas = L.tileLayer('/map/assets/map-tiles/atlas/{z}/{x}/{y}.jpg', commonOptions)
  const satellite = L.tileLayer('/map/assets/map-tiles/satelite/{z}/{x}/{y}.jpg', commonOptions)

  const baseMaps = {
    Atlas: atlas,
    Satellite: satellite,
  }

  L.control.layers(baseMaps, {}, { position: 'topright' }).addTo(map)

  satellite.addTo(map)

  mapInstance.value = map
})

onBeforeUnmount(() => {
  if (mapInstance.value) {
    mapInstance.value.remove()
  }
})
</script>

// src/shared/components/map/gta5-map.tsx
import 'leaflet/dist/leaflet.css'
import type { LatLngExpression } from 'leaflet'
import L from 'leaflet'
import type { HTMLAttributes, PropsWithChildren } from 'react'
import { forwardRef, useEffect, useImperativeHandle, useRef } from 'react'
import { LayersControl, MapContainer, useMap } from 'react-leaflet'
import { cn } from '#/shared/lib/utils'
import { createGta5Crs } from './custom-crs'
import { Gta5TileLayer } from './tile-layer'

export type GTA5MapHandle = {
  flyTo: (coords: LatLngExpression, zoom?: number, duration?: number) => void
}

/** Center/zoom framing the whole Los Santos map area. */
export const GTA5_OVERVIEW_CENTER: [number, number] = [-357, -375]
export const GTA5_OVERVIEW_ZOOM = 3

type Props = PropsWithChildren<{
  center?: LatLngExpression
  zoom?: number
  className?: HTMLAttributes<HTMLElement>['className']
}>

function Gta5ZoomControl() {
  const map = useMap()

  useEffect(() => {
    const control = L.control.zoom({ position: 'topleft' })
    control.addTo(map)
    return () => {
      control.remove()
    }
  }, [map])

  return null
}

export const GTA5Map = forwardRef<GTA5MapHandle, Props>(function GTA5Map(
  { children, center = GTA5_OVERVIEW_CENTER, zoom = GTA5_OVERVIEW_ZOOM, className },
  ref
) {
  const mapRef = useRef<L.Map | null>(null)

  useImperativeHandle(ref, () => ({
    flyTo: (coords: LatLngExpression, flyZoom = 5, duration = 1.2) => {
      mapRef.current?.flyTo(coords, flyZoom, { animate: true, duration })
    },
  }))

  return (
    <div
      className={cn(
        'gta5-map relative h-full w-full overflow-hidden rounded-2xl bg-[#0f1115] shadow-sm ring-1 ring-foreground/10',
        className
      )}
    >
      <MapContainer
        ref={mapRef}
        crs={createGta5Crs()}
        minZoom={1}
        maxZoom={5}
        center={center}
        zoom={zoom}
        zoomControl={false}
        className="h-full w-full"
        preferCanvas
      >
        <LayersControl position="topright" collapsed={false}>
          <LayersControl.BaseLayer name="Atlas">
            <Gta5TileLayer url="/map/assets/map-tiles/atlas/{z}/{x}/{y}.jpg" />
          </LayersControl.BaseLayer>
          <LayersControl.BaseLayer name="Satellite" checked>
            <Gta5TileLayer url="/map/assets/map-tiles/satelite/{z}/{x}/{y}.jpg" />
          </LayersControl.BaseLayer>
        </LayersControl>

        <Gta5ZoomControl />

        {children}
      </MapContainer>
    </div>
  )
})

export default GTA5Map
