// inertia/shared/components/ui/LinkText/LinkText.vue
<script lang="ts" setup>
import type { AnchorHTMLAttributes } from 'vue'
import { cn } from '@/lib/utils'
import { type InertiaLinkProps, Link } from '@inertiajs/vue3'
import { urlFor } from '@/client'
import type { InferRoutes, QueryParameters } from '@tuyau/core/types'
import type { registry } from '@generated/registry'

type BaseProps = {
  route?: keyof InferRoutes<typeof registry>
  params?: {
    params: readonly [string | number]
    query?: QueryParameters
  }
  class?: string
}

type ExternalProps = /* @vue-ignore */ AnchorHTMLAttributes & BaseProps & { external: true }
type InternalProps = InertiaLinkProps &
  BaseProps & {
    external?: false | undefined
  }

type Props = ExternalProps | InternalProps
const props = defineProps<Props>()
</script>
<template>
  <component
    :is="props.external ? 'a' : Link"
    v-bind="props"
    :href="!props.external && props.route ? urlFor(props.route as any, props.params) : props.href"
    :class="cn('font-medium text-primary underline underline-offset-4 cursor-pointer', props.class)"
  >
    <slot />
  </component>
</template>

// inertia/shared/components/link-text.tsx
import { cn } from '@/lib/utils'
import { Link } from '@adonisjs/inertia/react'
import { urlFor } from '@/client'
import type { InferRoutes, QueryParameters } from '@tuyau/core/types'
import type { registry } from '@generated/registry'
import type { AnchorHTMLAttributes } from 'react'
import type { InertiaLinkProps } from '@inertiajs/react'

type BaseProps = {
  route?: keyof InferRoutes<typeof registry>
  params?: {
    params: readonly [string | number]
    query?: QueryParameters
  }
  className?: string
  children?: React.ReactNode
}

type ExternalProps = AnchorHTMLAttributes<HTMLAnchorElement> & BaseProps & { external: true }
type InternalProps = InertiaLinkProps & BaseProps & { external?: false | undefined }
type Props = ExternalProps | InternalProps

export function LinkText(props: Props) {
  const { route, params, className, children, external, ...rest } = props

  const href = !external && route ? urlFor(route as any, params) : (props as ExternalProps).href

  if (external) {
    return (
      <a
        {...(rest as AnchorHTMLAttributes<HTMLAnchorElement>)}
        href={href}
        className={cn(
          'font-medium text-primary underline underline-offset-4 cursor-pointer',
          className
        )}
      >
        {children}
      </a>
    )
  }

  return (
    <Link
      {...(rest as InertiaLinkProps)}
      href={href!}
      className={cn(
        'font-medium text-primary underline underline-offset-4 cursor-pointer',
        className
      )}
    >
      {children}
    </Link>
  )
}
