// inertia/pages/about_us.vue
<template>
  <Head title="À propos" :image="BannerImage" />

  <PageBanner bg-color="hero-gradient" :bg-image="BannerImage" class="relative" py="24">
    <div class="relative z-10">
      <h1 class="text-5xl md:text-6xl font-bold mb-6 font-serif">
        <span class="text-gradient">Nous Sommes</span><br />
        Une Famille de Familles
      </h1>
      <p class="text-xl md:text-2xl opacity-90 leading-relaxed">
        Nous sommes quatre millions de catholiques. Nous sommes une Cité de Saints. Nous sommes le
        Peuple de Dieu de l'Archidiocèse de Los Santos.
      </p>
    </div>

    <div class="absolute -bottom-15 left-1/2 transform -translate-x-1/2">
      <ChevronDown class="w-6 h-6 animate-bounce" />
    </div>
  </PageBanner>

  <section class="py-20">
    <div class="container mx-auto px-4">
      <div class="max-w-7xl mx-auto">
        <div class="grid lg:grid-cols-2 gap-12 items-start">
          <div>
            <div class="text-center mb-16">
              <h2 class="text-4xl font-bold text-catholic-purple mb-6 font-serif">Notre Mission</h2>
              <div class="w-24 h-1 bg-catholic-gold mx-auto cross-divider mb-8"></div>
            </div>

            <div class="prose prose-lg max-w-none text-justify">
              <Typography>
                Nous, le Peuple de Dieu de l'Archidiocèse de Los Santos, recevons notre mission de
                poursuivre l'oeuvre rédemptrice de Jésus-Christ. Baptisés dans le Corps du Christ,
                confirmés dans l'Esprit Saint, nourris par la Parole et l'Eucharistie, nous
                partageons la mission du Christ, comme prêtres, prophètes et rois-serviteurs. Nous
                formons un seul corps avec l'Église catholique à travers le monde, en communion avec
                le Pape.
              </Typography>

              <Typography>
                Sous l'autorité pastorale de notre
                <LinkText route="archbishop.index">Archevêque</LinkText>, nous collaborons ensemble
                pour vivre et annoncer l'Évangile. Le Christ a proclamé le règne de Dieu. Nous
                sommes appelés à en être les instruments dans le monde. Nous nous engageons à bâtir
                une communauté de foi et d'amour.
              </Typography>

              <Typography>
                Avec le Christ, nous portons la Bonne Nouvelle aux pauvres. Nous nous engageons à
                combattre toutes les formes de pauvreté présentes parmi nous — spirituelles,
                économiques et morales.
              </Typography>

              <Typography>
                Avec le Christ, nous affirmons les liens qui nous unissent. Nous nous engageons à
                abattre les murs qui divisent.
              </Typography>

              <Typography>
                Nous consacrons nos paroisses, nos écoles, nos institutions, nos services et nos
                organisations à cette mission, sous la tendre protection de Marie, Reine des Saints.
              </Typography>
            </div>
          </div>
          <div class="relative lg:-mt-5 hidden lg:block">
            <div class="relative rounded-lg overflow-hidden shadow-2xl">
              <img
                src="@/assets/images/gta-world-2025-12-19-22-50-48.png"
                alt="People of God praying at Christmas Mass 2025"
                class="w-full h-auto objec-cover"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section
    class="relative py-20 bg-gray-50 bg-cover bg-center h-100 text-white"
    :style="`background-image: url(${VolunteerImage})`"
  >
    <div class="absolute inset-0 bg-black/60"></div>
    <div class="container relative z-10 mx-auto px-4">
      <div class="max-w-6xl mx-auto space-y-5">
        <Typography variant="h2" class="border-none pb-0 text-5xl text-catholic-gold font-bold">
          Notre impact
        </Typography>
        <Typography>
          Avec Catholic Charities, nous venons en aide à des millions d'enfants, de personnes âgées,
          de familles, d'hommes et de femmes, de migrants, de sans-abri et autres populations
          vulnérables, dans les comtés de Los Santos, de Ventura et de Santa Babara.
        </Typography>
        <Button variant="warning" size="lg" class="cursor-pointer" as-child>
          <Link route="vocations"><ArrowRight /> Devenez bénévole </Link>
        </Button>
      </div>
    </div>
  </section>

  <section class="py-15">
    <div class="container mx-auto px-4">
      <div class="max-w-7xl mx-auto">
        <div class="text-center mb-16">
          <h2 class="text-4xl font-bold text-primary mb-6 font-serif">Notre Histoire</h2>
          <div class="w-24 h-1 bg-catholic-gold mx-auto cross-divider mb-8"></div>
        </div>

        <div class="relative">
          <div class="float-left mr-8 mb-6 lg:w-1/2 w-full">
            <div class="relative rounded-lg overflow-hidden shadow-2xl">
              <img
                src="@/assets/images/la_placita_1814.png"
                alt="La Placita, first church of Los Santos"
                class="w-full h-auto object-cover"
              />
            </div>
          </div>
        </div>

        <div class="prose prose-lg max-w-none text-justify">
          <Typography>
            La première église de Haute-Andreas se composait de 21 missions, trois pueblos, quatre
            presidios et plusieurs asistencias. Chacun de ces lieux répondait à un plan précis. On
            peut retrouver ces fondations, au nord et au sud, le long de l'El Camino Real.
          </Typography>

          <Typography>
            L'Église de Notre Dame, la Reine des Saints, aussi connue sous le nom de La Placita, fut
            construite en 1814. C'est la première église de la ville de Los Santos, dont le nom
            abrégé provient du nom complet de la ville : El Pueblo de Nuestra Señora la Reina de los
            Santos (« Le Village de Notre-Dame, la Reine des Saints »). Si La Placita est la
            première église bâtie à Los Santos, la mission San Gabriel, érigée en 1771, fut la
            première église de notre Archidiocèse, avant même à la naissance de notre pays. Cette
            mission abrita le récemment canonisé saint Junìpero Serra, un missionnaire franciscain
            espagnol, qui a taversé le Mexique pour rejoindre San Andreas. L'influence franciscaine
            se perçoit encore aujourd'hui dans les noms de nombreuses rues, villes et quartiers de
            notre archidiocèse.
          </Typography>

          <div class="clear-both"></div>

          <div class="grid lg:grid-cols-2 gap-12 items-start">
            <div>
              <Typography>
                Sur le plan spirituel, saint Junìpero est reconnu comme l'un des fondateurs de notre
                Église à Los Santos, dans notre État et même dans notre pays. Il commença son oeuvre
                missionnaire à Mexico où il rendit visite à la relique de la Tilma de Notre-Dame de
                Guadalupe, patronne des Amériques. Nous avons la grâce immense de puvoir vénérer
                Notre-Dame, tout comme saint Junìpero, devant une des reliques de la Tilma
                précieusement conservée dans l'une des chapelles latérales de la Cathédrale
                Notre-Dame-des-Saints.
              </Typography>

              <Typography>
                Aujourd'hui, l'Archidiocèse de Los Santos comprend trois comtés situés au sud de San
                Andreas : Los Santos, Ventura et Santa Barbara. Son territoire s'étend de la limite
                du nord du comté de Santa Barbara, près de Maria, jusqu'à la limite sud de l'île du
                comté de Los Santos. Il couvre une superficie de 22 430 km². En 2005, la population
                catholique s'élevait à 4 349 267 fidèles sur un total de 11 258 600 habitants.
                L'archidiocèse compte 288 paroisses réparties dans 120 villes.
              </Typography>

              <Typography>
                Il y a également 30 missions et chapelles, ainsi que 16 églises catholiques de rite
                oriental. Au total, l'Archidiocèse dispose de 214 écoles primaires et 51 lycées
                catholiques, le plus vaste réseau scolaire de l'État de San Andreas. Dans ce
                contexte culturellement très diversifié, des services éthniques sont proposés à 72
                communautés différentes. Cela inclut l'accompagnement clrical, la liturgie, les
                services sociaux, des ressources, des conseils et des initiatives culturelles.
              </Typography>
            </div>
            <div class="relative hidden lg:block w-95">
              <div class="relative rounded-lg overflow-hidden shadow-2xl">
                <img
                  src="@/assets/images/st_junipero_serra.png"
                  alt="St. Junìpero Serra, San Andreas Catholic Missions Founder"
                  class="w-full h-auto objec-cover"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import Head from '@/shared/components/AppHead.vue'
import { Button } from '@/shared/components/ui/button'
import VolunteerImage from '@/assets/images/thanksgiving2024.png'
import { ChevronDown, ArrowRight } from 'lucide-vue-next'
import PageBanner from '@/shared/components/layout/PageBanner.vue'
import BannerImage from '@/assets/images/olacathedral-cross.png'
import { Typography } from '@/shared/components/ui/typography'
import { LinkText } from '@/shared/components/ui/LinkText'
import { Link } from '@adonisjs/inertia/vue'
</script>

<style scoped>
.relative img {
  transition: transform 0.3s ease;
}

.relative:hover img {
  transform: scale(1.02);
}

.order-2.lg\:order-1 .absolute.-bottom-6 {
  right: auto;
  left: -1.5rem;
}
</style>

// inertia/pages/about-us.tsx
import { Link } from '@adonisjs/inertia/react'
import { ArrowRight, ChevronDown } from 'lucide-react'
import { Button } from '@/shared/components/ui/button'
import { Typography } from '@/shared/components/ui/typography'
import HeroSection from '@/shared/components/layout/default/hero-section'
import Head from '@/shared/components/app-head'
import BannerImage from '@/assets/images/olacathedral-cross.png'
import VolunteerImage from '@/assets/images/thanksgiving2024.png'
import MassImage from '@/assets/images/gta-world-2025-12-19-22-50-48.png'
import LaPlacitaImage from '@/assets/images/la_placita_1814.png'
import StJuniperoImage from '@/assets/images/st_junipero_serra.png'
import { LinkText } from '@/shared/components/link-text'

export default function AboutPage() {
  return (
    <>
      <Head title="À propos" />

      <HeroSection bgColor="hero-gradient" bgImage={BannerImage} className="relative" py="24">
        <div className="relative z-10">
          <h1 className="text-5xl md:text-6xl font-bold mb-6 font-serif">
            <span className="text-gradient">Nous Sommes</span>
            <br />
            Une Famille de Familles
          </h1>
          <p className="text-xl md:text-2xl opacity-90 leading-relaxed">
            Nous sommes quatre millions de catholiques. Nous sommes une Cité de Saints. Nous sommes
            le Peuple de Dieu de l'Archidiocèse de Los Santos.
          </p>
        </div>

        <div className="absolute -bottom-15 left-1/2 transform -translate-x-1/2">
          <ChevronDown className="w-6 h-6 animate-bounce" />
        </div>
      </HeroSection>

      <section className="py-20">
        <div className="container mx-auto px-4">
          <div className="max-w-7xl mx-auto">
            <div className="grid lg:grid-cols-2 gap-12 items-start">
              <div>
                <div className="text-center mb-16">
                  <h2 className="text-4xl font-bold text-catholic-purple mb-6 font-serif">
                    Notre Mission
                  </h2>
                  <div className="w-24 h-1 bg-catholic-gold mx-auto cross-divider mb-8" />
                </div>

                <div className="prose prose-lg max-w-none text-justify">
                  <Typography>
                    Nous, le Peuple de Dieu de l'Archidiocèse de Los Santos, recevons notre mission
                    de poursuivre l'oeuvre rédemptrice de Jésus-Christ. Baptisés dans le Corps du
                    Christ, confirmés dans l'Esprit Saint, nourris par la Parole et l'Eucharistie,
                    nous partageons la mission du Christ, comme prêtres, prophètes et
                    rois-serviteurs. Nous formons un seul corps avec l'Église catholique à travers
                    le monde, en communion avec le Pape.
                  </Typography>

                  <Typography>
                    Sous l'autorité pastorale de notre{' '}
                    <LinkText route="archbishop.index">Archevêque</LinkText>, nous collaborons
                    ensemble pour vivre et annoncer l'Évangile. Le Christ a proclamé le règne de
                    Dieu. Nous sommes appelés à en être les instruments dans le monde. Nous nous
                    engageons à bâtir une communauté de foi et d'amour.
                  </Typography>

                  <Typography>
                    Avec le Christ, nous portons la Bonne Nouvelle aux pauvres. Nous nous engageons
                    à combattre toutes les formes de pauvreté présentes parmi nous — spirituelles,
                    économiques et morales.
                  </Typography>

                  <Typography>
                    Avec le Christ, nous affirmons les liens qui nous unissent. Nous nous engageons
                    à abattre les murs qui divisent.
                  </Typography>

                  <Typography>
                    Nous consacrons nos paroisses, nos écoles, nos institutions, nos services et nos
                    organisations à cette mission, sous la tendre protection de Marie, Reine des
                    Saints.
                  </Typography>
                </div>
              </div>

              <div className="relative lg:-mt-5 hidden lg:block">
                <div className="relative rounded-lg overflow-hidden shadow-2xl transition-transform duration-300 hover:scale-[1.02]">
                  <img
                    src={MassImage}
                    alt="People of God praying at Christmas Mass 2025"
                    className="w-full h-auto object-cover"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Impact */}
      <section
        className="relative py-20 bg-gray-50 bg-cover bg-center h-100 text-white"
        style={{ backgroundImage: `url(${VolunteerImage})` }}
      >
        <div className="absolute inset-0 bg-black/60" />
        <div className="container relative z-10 mx-auto px-4">
          <div className="max-w-6xl mx-auto space-y-5">
            <Typography
              variant="h2"
              className="border-none pb-0 text-5xl text-catholic-gold font-bold"
            >
              Notre impact
            </Typography>
            <Typography>
              Avec Catholic Charities, nous venons en aide à des millions d'enfants, de personnes
              âgées, de familles, d'hommes et de femmes, de migrants, de sans-abri et autres
              populations vulnérables, dans les comtés de Los Santos, de Ventura et de Santa Babara.
            </Typography>
            <Button variant="warning" size="lg" className="cursor-pointer" asChild>
              <Link route="charities.index">
                <ArrowRight /> Devenez bénévole
              </Link>
            </Button>
          </div>
        </div>
      </section>

      {/* Histoire */}
      <section className="py-15">
        <div className="container mx-auto px-4">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-4xl font-bold text-primary mb-6 font-serif">Notre Histoire</h2>
              <div className="w-24 h-1 bg-catholic-gold mx-auto cross-divider mb-8" />
            </div>

            <div className="relative">
              <div className="float-left mr-8 mb-6 lg:w-1/2 w-full">
                <div className="relative rounded-lg overflow-hidden shadow-2xl transition-transform duration-300 hover:scale-[1.02]">
                  <img
                    src={LaPlacitaImage}
                    alt="La Placita, first church of Los Santos"
                    className="w-full h-auto object-cover"
                  />
                </div>
              </div>
            </div>

            <div className="prose prose-lg max-w-none text-justify">
              <Typography>
                La première église de Haute-Andreas se composait de 21 missions, trois pueblos,
                quatre presidios et plusieurs asistencias. Chacun de ces lieux répondait à un plan
                précis. On peut retrouver ces fondations, au nord et au sud, le long de l'El Camino
                Real.
              </Typography>

              <Typography>
                L'Église de Notre Dame, la Reine des Saints, aussi connue sous le nom de La Placita,
                fut construite en 1814. C'est la première église de la ville de Los Santos, dont le
                nom abrégé provient du nom complet de la ville : El Pueblo de Nuestra Señora la
                Reina de los Santos (« Le Village de Notre-Dame, la Reine des Saints »). Si La
                Placita est la première église bâtie à Los Santos, la mission San Gabriel, érigée en
                1771, fut la première église de notre Archidiocèse, avant même à la naissance de
                notre pays. Cette mission abrita le récemment canonisé saint Junìpero Serra, un
                missionnaire franciscain espagnol, qui a taversé le Mexique pour rejoindre San
                Andreas. L'influence franciscaine se perçoit encore aujourd'hui dans les noms de
                nombreuses rues, villes et quartiers de notre archidiocèse.
              </Typography>

              <div className="clear-both" />

              <div className="grid lg:grid-cols-2 gap-12 items-start">
                <div>
                  <Typography>
                    Sur le plan spirituel, saint Junìpero est reconnu comme l'un des fondateurs de
                    notre Église à Los Santos, dans notre État et même dans notre pays. Il commença
                    son oeuvre missionnaire à Mexico où il rendit visite à la relique de la Tilma de
                    Notre-Dame de Guadalupe, patronne des Amériques. Nous avons la grâce immense de
                    puvoir vénérer Notre-Dame, tout comme saint Junìpero, devant une des reliques de
                    la Tilma précieusement conservée dans l'une des chapelles latérales de la
                    Cathédrale Notre-Dame-des-Saints.
                  </Typography>

                  <Typography>
                    Aujourd'hui, l'Archidiocèse de Los Santos comprend trois comtés situés au sud de
                    San Andreas : Los Santos, Ventura et Santa Barbara. Son territoire s'étend de la
                    limite du nord du comté de Santa Barbara, près de Maria, jusqu'à la limite sud
                    de l'île du comté de Los Santos. Il couvre une superficie de 22 430 km². En
                    2005, la population catholique s'élevait à 4 349 267 fidèles sur un total de 11
                    258 600 habitants. L'archidiocèse compte 288 paroisses réparties dans 120
                    villes.
                  </Typography>

                  <Typography>
                    Il y a également 30 missions et chapelles, ainsi que 16 églises catholiques de
                    rite oriental. Au total, l'Archidiocèse dispose de 214 écoles primaires et 51
                    lycées catholiques, le plus vaste réseau scolaire de l'État de San Andreas. Dans
                    ce contexte culturellement très diversifié, des services éthniques sont proposés
                    à 72 communautés différentes. Cela inclut l'accompagnement clrical, la liturgie,
                    les services sociaux, des ressources, des conseils et des initiatives
                    culturelles.
                  </Typography>
                </div>

                <div className="relative hidden lg:block w-95">
                  <div className="relative rounded-lg overflow-hidden shadow-2xl transition-transform duration-300 hover:scale-[1.02]">
                    <img
                      src={StJuniperoImage}
                      alt="St. Junìpero Serra, San Andreas Catholic Missions Founder"
                      className="w-full h-auto object-cover"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}
