// inertia/pages/parishes.tsx
import { Head } from '@inertiajs/react'
import { lazy, startTransition, Suspense, useRef } from 'react'
import { MapPin } from 'lucide-react'
import { Card, CardContent } from '@/shared/components/ui/card'
import { Typography } from '@/shared/components/ui/typography'
import { parishes } from '@/shared/constants/parishes.constants'
import HeroSection from '@/shared/components/layout/default/hero-section'
import type { MapMarkerHandle } from '@/shared/components/map/map-marker'
import type { GTA5MapHandle } from '@/shared/components/map/gta5-map'
import { MapFallback } from '@/shared/components/map/map-fallback'

const GTA5Map = lazy(() => import('@/shared/components/map/gta5-map'))
const MapMarker = lazy(() => import('@/shared/components/map/map-marker'))

export default function ParishesPage() {
  const mapScrollTarget = useRef<HTMLDivElement>(null)
  const mapRef = useRef<GTA5MapHandle>(null)
  const markerRefs = useRef<Array<MapMarkerHandle | null>>([])

  const focusParish = (index: number) => {
    startTransition(() => {
      const parish = parishes[index]

      if (mapScrollTarget.current) {
        startTransition(() => {
          mapScrollTarget.current!.scrollIntoView({ behavior: 'smooth', block: 'center' })
        })
      }

      if (mapRef.current) {
        startTransition(() => {
          mapRef.current!.flyTo(parish.coords as [number, number], 5)
        })
      }

      setTimeout(() => {
        const marker = markerRefs.current[index]
        if (marker) marker.openPopup()
      }, 600)
    })
  }

  return (
    <>
      <Head title="Nos Paroisses" />

      <HeroSection bgColor="bg-linear-to-r from-catholic-purple to-catholic-blue" py="16">
        <h1 className="text-4xl md:text-5xl font-bold mb-4 font-serif">Nos Paroisses</h1>
        <p className="text-xl opacity-90">
          Découvrez les communautés de foi qui composent notre archidiocèse
        </p>
      </HeroSection>

      <section className="py-16">
        <div className="container max-w-7xl mx-auto px-4">
          <Typography variant="h2" className="pb-10 text-catholic-purple font-bold">
            Doyenné Notre-Dame-des-Saints
          </Typography>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {parishes.map((parish, index) => (
              <Card
                key={parish.id}
                onClick={() => focusParish(index)}
                className="card-hover cursor-pointer transition-all hover:ring-2 hover-ring-catholic-gold pt-0"
              >
                {parish.image ? (
                  <div
                    className="aspect-video bg-cover bg-center"
                    style={{ backgroundImage: `url(${parish.image})` }}
                  />
                ) : (
                  <div className="aspect-video bg-gray-200 rounded-t-lg" />
                )}
                <CardContent className="p-6">
                  <h3 className="font-bold text-xl mb-2 text-catholic-purple">{parish.name}</h3>
                  <div className="flex items-start gap-2 mb-3 text-sm text-gray-600">
                    <MapPin className="w-4 h-4 mt-0.5 shrink-0" />
                    <span>{parish.address}</span>
                  </div>
                  {parish.description && (
                    <p className="text-base text-justify leading-7 py-2">{parish.description}</p>
                  )}
                  <div className="mb-4">
                    <h4 className="inline font-semibold mb-2 text-sm">{parish.priestOffice} :</h4>
                    <div className="inline ml-2 space-y-1 text-xs">{parish.priestName}</div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          <div ref={mapScrollTarget} className="mt-12">
            <Suspense fallback={<MapFallback />}>
              <GTA5Map
                ref={mapRef}
                center={[-709.148, -759.794]}
                zoom={3}
                className="h-[500px] rounded-xl border-2 border-catholic-gold shadow-xl"
              >
                {parishes.map((parish, index) => (
                  <MapMarker
                    key={parish.id}
                    ref={(el: MapMarkerHandle | null) => {
                      markerRefs.current[index] = el
                    }}
                    position={parish.coords}
                  >
                    <div className="p-2">
                      <h4 className="font-bold">{parish.name}</h4>
                    </div>
                  </MapMarker>
                ))}
              </GTA5Map>
            </Suspense>
          </div>
        </div>
      </section>
    </>
  )
}

// inertia/pages/find/parishes.vue
<template>
  <Head title="Nos Paroisses" />

  <PageBanner bg-color="bg-gradient-to-r from-catholic-purple to-catholic-blue" py="16">
    <h1 class="text-4xl md:text-5xl font-bold mb-4 font-serif">Nos Paroisses</h1>
    <p class="text-xl opacity-90">
      Découvrez les communautés de foi qui composent notre archidiocèse
    </p>
  </PageBanner>

  <section class="py-16">
    <div class="container max-w-7xl mx-auto px-4">
      <h2
        class="scroll-m-20 border-b pb-10 text-3xl text-catholic-purple font-bold tracking-tight transition-colors first:mt-0"
      >
        Doyenné Notre-Dame-des-Saints
      </h2>
      <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
        <Card v-for="parish in parishes" :key="parish.id" class="card-hover pt-0">
          <div
            v-if="parish.image"
            class="aspect-video bg-cover bg-center"
            :style="`background-image: url(${parish.image})`"
          ></div>
          <div v-else class="aspect-video bg-gray-200 rounded-t-lg"></div>
          <CardContent class="p-6">
            <h3 class="font-bold text-xl mb-2 text-catholic-purple">{{ parish.name }}</h3>
            <div class="flex items-start gap-2 mb-3 text-sm text-gray-600">
              <MapPin class="w-4 h-4 mt-0.5 flex-shrink-0" />
              <span>{{ parish.address }}</span>
            </div>

            <p class="text-base text-justify leading-7 py-2">{{ parish.description }}</p>

            <div class="mb-4">
              <h4 class="inline font-semibold mb-2 text-sm">{{ parish.priestOffice }} :</h4>
              <div class="inline ml-2 space-y-1 text-xs">
                {{ parish.priestName }}
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import PageBanner from '@/components/layout/PageBanner.vue'
import { Card, CardContent } from '@/components/ui/card'
import { Head } from '@inertiajs/vue3'
import { MapPin } from 'lucide-vue-next'
import { parishes } from '@/constants/parishes.constants'
</script>
