// inertia/features/register-parishioner/components/form/parishioner-form.tsx
import { useAppForm } from '@/lib/form'
import { registerParishionerFormOpts } from '@/features/register-parishioner/constants/form_opts'
import { urlFor } from '@/lib/client'
import { router } from '@inertiajs/react'
import { usePageProps } from '@/shared/hooks/use_page_props'
import { serverErrorsFormConvertor } from '@/lib/utils'
import { Button } from '@/shared/components/ui/button'
import { LoaderCircle } from 'lucide-react'
import { Separator } from '@/shared/components/ui/separator'
import { ParishionerPersonalInfoFields } from '@/features/register-parishioner/components/form/fields/parishioner-personal-info-fields'
import { ParishionerContactInfoFields } from '@/features/register-parishioner/components/form/fields/parishioner-contact-info-fields'
import { ParishionerAddressFields } from '@/features/register-parishioner/components/form/fields/parishioner-address-fields'
import { ParishionerReligionFields } from '@/features/register-parishioner/components/form/fields/parishioner-religion-fields'
import { ParishionerHouseholdFields } from '@/features/register-parishioner/components/form/fields/parishioner-household-fields'
import { ParishionerOOCFields } from '@/features/register-parishioner/components/form/fields/parishioner-ooc-fields'
import { ParishionerMessageField } from '@/features/register-parishioner/components/form/fields/parishioner-message-field'

export function ParishionerForm() {
  const props = usePageProps<{ errors: { E_REGISTER_PARISHIONER_ERROR?: string } }>()

  const form = useAppForm({
    ...registerParishionerFormOpts(props.user!.currentCharacter!),
    onSubmit: ({ value }) => {
      router.post(urlFor('registerParishioner.submit'), value, {
        preserveScroll: true,
        preserveState: true,
        onSuccess: () => {
          form.reset()
        },
        onError: (err) => {
          form.setErrorMap({
            onSubmit: serverErrorsFormConvertor(err),
          })
        },
      })
    },
  })

  const onSubmit = (e: React.SubmitEvent) => {
    e.preventDefault()
    form.handleSubmit()
  }

  return (
    <form id="register-parishioner-form" onSubmit={onSubmit} className="space-y-8">
      <ParishionerPersonalInfoFields form={form} characterId={props.user!.currentCharacter!.id} />

      <ParishionerContactInfoFields form={form} />

      <ParishionerAddressFields form={form} />

      <ParishionerReligionFields form={form} />

      <ParishionerHouseholdFields form={form} />

      <ParishionerMessageField form={form} />

      <Separator />

      <ParishionerOOCFields form={form} />

      <div className="flex justify-end pt-6 border-t">
        <form.Subscribe
          selector={(state) => [state.canSubmit, state.isSubmitting, state.isValidating]}
        >
          {([canSubmit, isSubmitting, isValidating]) => (
            <Button
              type="submit"
              form="register-parishioner-form"
              size="lg"
              disabled={!canSubmit || isValidating}
            >
              {isSubmitting ? (
                <>
                  <LoaderCircle className="animate-spin" />
                  Soumission...
                </>
              ) : (
                "Soumettre l'enregistrement"
              )}
            </Button>
          )}
        </form.Subscribe>
      </div>
    </form>
  )
}

// inertia/features/register-parishioner/components/form/ParishionerForm.vue
<template>
  <form @submit="onSubmit" class="space-y-8">
    <ParishionerPersonalInfoSection />

    <ParishionerContactInfoSection />

    <ParishionerAddressSection />

    <ParishionerReligionSection />

    <ParishionerHouseholdMembersSection />

    <ParishionerAdditionalInfoSection />

    <Separator />

    <ParishionerOOCSection />

    <div class="flex justify-end pt-6 border-t">
      <Button
        type="submit"
        size="lg"
        :disabled="isSubmitting || isValidating || meta.pending || !meta.valid || !meta.dirty"
      >
        <template v-if="isSubmitting">
          <LoaderCircle class="animate-spin" />
          Soumission...
        </template>
        <template v-else>Soumettre l'enregistrement</template>
      </Button>
    </div>
  </form>
</template>

<script setup lang="ts">
import { Separator } from '@/shared/components/ui/separator'
import { LoaderCircle } from 'lucide-vue-next'
import ParishionerOOCSection from '@/features/register-parishioner/components/form/ParishionerOOCSection.vue'
import { Button } from '@/shared/components/ui/button'
import ParishionerContactInfoSection from '@/features/register-parishioner/components/form/ParishionerContactInfoSection.vue'
import ParishionerAddressSection from '@/features/register-parishioner/components/form/ParishionerAddressSection.vue'
import ParishionerAdditionalInfoSection from '@/features/register-parishioner/components/form/ParishionerAdditionalInfoSection.vue'
import ParishionerReligionSection from '@/features/register-parishioner/components/form/ParishionerReligionSection.vue'
import ParishionerHouseholdMembersSection from '@/features/register-parishioner/components/form/ParishionerHouseholdMembersSection.vue'
import { useParishionerForm } from '@/features/register-parishioner/composables/use_parishioner_form'
import { useParishionerFormSubmission } from '@/features/register-parishioner/composables/use_parishioner_form_submission'
import ParishionerPersonalInfoSection from '@/features/register-parishioner/components/form/ParishionerPersonalInfoSection.vue'

const form = useParishionerForm()
const { isSubmitting, isValidating, meta } = form
const { onSubmit } = useParishionerFormSubmission(form)
</script>
