// inertia/pages/dashboard/posts/create.tsx
import Head from '@/shared/components/app-head'
import { Button } from '@/shared/components/ui/button'
import type { InertiaProps } from '@/types'
import { Link } from '@adonisjs/inertia/react'
import { ArrowLeft } from 'lucide-react'
import { CreatePostForm } from '@/features/posts/components/dashboard/form/create-post-form'

type PageProps = InertiaProps

export default function DashboardCreatePostForm({}: PageProps) {
  return (
    <>
      <Head title="Créer un article" />

      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" asChild>
            <Link route="dashboard.dashboard_posts.index">
              <ArrowLeft className="h-4 w-4" />
            </Link>
          </Button>
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Créer un article</h1>
            <p className="text-gray-500 dark:text-gray-400">
              Ajoutez un nouvel article à votre site
            </p>
          </div>
        </div>

        <CreatePostForm />
      </div>
    </>
  )
}

// inertia/pages/dashboard/articles/create.vue
<template>
  <Head title="Créer un article" />

  <div class="space-y-6">
    <div class="flex items-center gap-4">
      <Button variant="ghost" size="icon" as-child>
        <Link :href="urlFor('dashboard.dashboard_articles.index')">
          <ArrowLeft class="h-4 w-4" />
        </Link>
      </Button>
      <div>
        <h1 class="text-3xl font-bold tracking-tight">Créer un article</h1>
        <p class="text-gray-500 dark:text-gray-400">Ajoutez un nouvel article à votre site</p>
      </div>
    </div>

    <DashboardCreatePostForm />
  </div>
</template>
<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3'
import { Button } from '@/shared/components/ui/button'
import { ArrowLeft } from 'lucide-vue-next'
import { urlFor } from '@/client'
import DashboardCreatePostForm from '@/features/posts/components/dashboard/form/DashboardCreatePostForm.vue'
</script>
