// inertia/features/jobs/components/form/dashboard/JobDashboardTitleSlugFields.vue
<template>
  <VeeField v-slot="{ field, errors }" name="title">
    <Field :data-invalid="!!errors.length">
      <FieldLabel :for="field.name">Titre *</FieldLabel>
      <Input
        :id="field.name"
        :model-value="field.value"
        @update:model-value="field.onChange"
        @blur="field.onBlur"
        placeholder="Titre de l'emploi"
        required
        :aria-invalid="!!errors.length"
      />
      <FieldError v-if="errors.length" :errors="errors" />
    </Field>
  </VeeField>

  <VeeField v-slot="{ field, errors }" name="slug">
    <Field :data-invalid="!!errors.length">
      <FieldLabel :for="field.name">Slug</FieldLabel>
      <Input
        :id="field.name"
        :model-value="field.value"
        @update:model-value="field.onChange"
        @blur="
          (e: Event) => {
            generateSlug()
            field.onBlur(e)
          }
        "
        placeholder="url-de-loffre"
        :aria-invalid="!!errors.length"
      />
      <FieldDescription>Laissez vide pour générer automatiquement</FieldDescription>
      <FieldError v-if="errors.length" :errors="errors" />
    </Field>
  </VeeField>
</template>
<script setup lang="ts">
import { Field as VeeField, useFormContext } from 'vee-validate'
import { Field, FieldDescription, FieldError, FieldLabel } from '@/shared/components/ui/field'
import { Input } from '@/shared/components/ui/input'

const form = useFormContext()

const props = defineProps<{
  autoSlug?: boolean
}>()

const generateSlug = () => {
  if (props.autoSlug || form.values.slug || !form.values.title) return
  form.setFieldValue(
    'slug',
    form.values.title
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
  )
}
</script>

// inertia/features/jobs/components/form/dashboard/fields/job-dashboard-title-slug-fields.tsx
import { withForm } from '@/lib/form'
import { createJobFormOpts } from '@/features/jobs/constants/form_opts'
import { Field, FieldDescription, FieldError, FieldLabel } from '@/shared/components/ui/field'
import { Input } from '@/shared/components/ui/input'

export const JobDashboardTitleSlugFields = withForm({
  ...createJobFormOpts,
  props: {
    autoSlug: true,
  },
  render: ({ form, autoSlug }) => {
    const generateSlug = () => {
      if (!autoSlug || form.state.values.slug || !form.state.values.title) return
      const slug = form.state.values.title
        .toLowerCase()
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')

      form.setFieldValue('slug', slug)
    }

    return (
      <>
        <form.AppField name="title">
          {(field) => {
            const isInvalid = field.state.meta.isTouched && !field.state.meta.isValid
            return (
              <Field data-invalid={isInvalid}>
                <FieldLabel htmlFor={field.name}>Titre *</FieldLabel>
                <Input
                  id={field.name}
                  name={field.name}
                  value={field.state.value}
                  onBlur={() => {
                    generateSlug()
                    field.handleBlur()
                  }}
                  onChange={(e) => field.handleChange(e.target.value)}
                  aria-invalid={isInvalid}
                  placeholder="Titre de l'emploi"
                />
                {isInvalid && <FieldError errors={field.state.meta.errors} />}
              </Field>
            )
          }}
        </form.AppField>

        <form.AppField name="slug">
          {(field) => {
            const isInvalid = field.state.meta.isTouched && !field.state.meta.isValid
            return (
              <Field data-invalid={isInvalid}>
                <FieldLabel htmlFor={field.name}>Slug</FieldLabel>
                <Input
                  id={field.name}
                  name={field.name}
                  value={field.state.value}
                  onBlur={field.handleBlur}
                  onChange={(e) => field.handleChange(e.target.value)}
                  aria-invalid={isInvalid}
                  placeholder="url-de-loffre"
                />
                <FieldDescription>Laissez vide pour générer automatiquement</FieldDescription>
                {isInvalid && <FieldError errors={field.state.meta.errors} />}
              </Field>
            )
          }}
        </form.AppField>
      </>
    )
  },
})
