// inertia/features/jobs/components/form/dashboard/JobDashboardForm.vue
<template>
  <form :id="id" @submit="onSubmit">
    <div class="grid gap-6 lg:grid-cols-3">
      <div class="lg:col-span-2 space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>Contenu</CardTitle>
            <CardDescription>
              Renseignez les informations principales de l'offre d'emploi
            </CardDescription>
          </CardHeader>
          <CardContent class="space-y-4">
            <VeeField v-slot="{ field, errors }" name="employmentType">
              <Field orientation="responsive" :data-invalid="!!errors.length">
                <FieldContent>
                  <FieldLabel :for="field.name">Type d'emploi *</FieldLabel>
                  <FieldError v-if="errors.length" :errors="errors" />
                </FieldContent>
                <Select
                  :model-value="field.value"
                  @update:model-value="field.onChange"
                  @blur="field.onBlur"
                >
                  <SelectTrigger :id="field.name" class="w-full" :aria-invalid="!!errors.length">
                    <SelectValue placeholder="Sélectionner un type" />
                  </SelectTrigger>
                  <SelectContent position="item-aligned">
                    <SelectItem
                      v-for="(label, index) of EMPLOYMENT_TYPE"
                      :key="index"
                      :value="index"
                    >
                      {{ label }}
                    </SelectItem>
                  </SelectContent>
                </Select>
              </Field>
            </VeeField>

            <JobDashboardTitleSlugFields :auto-slug="autoSlug" />

            <VeeField v-slot="{ field, errors }" name="summary">
              <Field :data-invalid="!!errors.length">
                <FieldLabel :for="field.name">Description</FieldLabel>
                <Textarea
                  :id="field.name"
                  :model-value="field.value"
                  @update:model-value="field.onChange"
                  @blur="field.onBlur"
                  placeholder="Courte description de l'emploi..."
                  :rows="3"
                  :aria-invalid="!!errors.length"
                />
                <FieldError v-if="errors.length" :errors="errors" />
              </Field>
            </VeeField>

            <JobDashboardAffiliationFields />

            <VeeField v-slot="{ field, errors }" name="salary">
              <Field :data-invalid="!!errors.length">
                <FieldLabel :for="field.name">Salaire hebdomadaire *</FieldLabel>
                <NumberField
                  class="gap-2"
                  :min="0"
                  :format-options="{
                    style: 'currency',
                    currency: 'USD',
                    currencyDisplay: 'symbol',
                    currencySign: 'accounting',
                  }"
                  :model-value="field.value"
                  @update:model-value="
                    (v) => {
                      if (v) {
                        form.setFieldValue('salary', v)
                      } else {
                        form.setFieldValue('salary', undefined as unknown as number)
                      }
                    }
                  "
                >
                  <NumberFieldContent>
                    <NumberFieldDecrement />
                    <NumberFieldInput />
                    <NumberFieldIncrement />
                  </NumberFieldContent>
                </NumberField>
                <FieldError v-if="errors.length" :errors="errors" />
              </Field>
            </VeeField>

            <JobDashboardResponsibilitiesField />

            <JobDashboardRequirementsField />

            <JobDashboardSkillsField />
          </CardContent>
        </Card>
      </div>

      <JobDashboardFormSidebar :variant="variant" :form-id="id" />
    </div>
  </form>
</template>

<script setup lang="ts">
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/shared/components/ui/card'
import { Textarea } from '@/shared/components/ui/textarea'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/shared/components/ui/select'
import { Field as VeeField } from 'vee-validate'
import { Field, FieldContent, FieldError, FieldLabel } from '@/shared/components/ui/field'
import {
  NumberField,
  NumberFieldContent,
  NumberFieldDecrement,
  NumberFieldIncrement,
  NumberFieldInput,
} from '@/shared/components/ui/number-field'
import { EMPLOYMENT_TYPE } from '#shared/constants/employment.constants'
import {
  useDashboardCreateJobForm,
  useDashboardEditJobForm,
} from '@/features/jobs/composables/dashboard/use_dashboard_job_form'
import JobDashboardResponsibilitiesField from '@/features/jobs/components/form/dashboard/JobDashboardResponsibilitiesField.vue'
import JobDashboardRequirementsField from '@/features/jobs/components/form/dashboard/JobDashboardRequirementsField.vue'
import JobDashboardAffiliationFields from '@/features/jobs/components/form/dashboard/JobDashboardAffiliationFields.vue'
import JobDashboardFormSidebar from '@/features/jobs/components/form/dashboard/JobDashboardFormSidebar.vue'
import JobDashboardTitleSlugFields from '@/features/jobs/components/form/dashboard/JobDashboardTitleSlugFields.vue'
import JobDashboardSkillsField from '@/features/jobs/components/form/dashboard/JobDashboardSkillsField.vue'

const props = withDefaults(
  defineProps<{
    form: ReturnType<typeof useDashboardCreateJobForm> | ReturnType<typeof useDashboardEditJobForm>
    id?: string
    autoSlug?: boolean
    variant?: 'create' | 'edit'
  }>(),
  {
    id: 'create-job-offer-form',
    autoSlug: true,
    variant: 'create' as const,
  }
)

const emit = defineEmits<{
  (e: 'submit', values: Record<string, any>): void
}>()

const onSubmit = props.form.handleSubmit((values) => {
  emit('submit', values)
})
</script>

// inertia/features/jobs/components/form/dashboard/job-dashboard-form.tsx
import { withForm } from '@/lib/form'
import { createJobFormOpts } from '@/features/jobs/constants/form_opts'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/shared/components/ui/card'
import { Field, FieldContent, FieldError, FieldLabel } from '@/shared/components/ui/field'
import { EMPLOYMENT_TYPE } from '#shared/constants/employment.constants'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/shared/components/ui/select'
import { Textarea } from '@/shared/components/ui/textarea'
import {
  NumberField,
  NumberFieldContent,
  NumberFieldDecrement,
  NumberFieldIncrement,
  NumberFieldInput,
} from '@/shared/components/ui/number-field'
import { JobDashboardTitleSlugFields } from '@/features/jobs/components/form/dashboard/fields/job-dashboard-title-slug-fields'
import { JobDashboardResponsibilitiesField } from '@/features/jobs/components/form/dashboard/fields/job-dashboard-responsibilities-field'
import { JobDashboardRequirementsField } from '@/features/jobs/components/form/dashboard/fields/job-dashboard-requirements-field'
import { JobDashboardSkillsField } from '@/features/jobs/components/form/dashboard/fields/job-dashboard-skills-field'
import { JobDashboardFormSidebar } from '@/features/jobs/components/form/dashboard/job-dashboard-form-sidebar'
import { JobDashboardAffiliationFields } from '@/features/jobs/components/form/dashboard/fields/job-dashboard-affiliation-fields'

type Props = { id?: string; autoSlug?: boolean; variant?: 'create' | 'edit' }

export const JobDashboardForm = withForm({
  ...createJobFormOpts,
  props: {
    id: 'create-job-offer-form',
    autoSlug: true,
    variant: 'create' as 'create' | 'edit',
  } as Props,
  render: ({ form, id = 'create-job-offer-form', autoSlug = true, variant = 'create' }) => {
    return (
      <div className="grid gap-6 lg:grid-cols-3">
        <div className="lg:col-span-2 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Contenu</CardTitle>
              <CardDescription>
                Renseignez les informations principales de l'offre d'emploi
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <form.AppField name="employmentType">
                {(field) => {
                  const isInvalid = field.state.meta.isTouched && !field.state.meta.isValid
                  return (
                    <Field data-invalid={isInvalid}>
                      <FieldContent>
                        <FieldLabel htmlFor={field.name}>Type d'emploi *</FieldLabel>
                        {isInvalid && <FieldError errors={field.state.meta.errors} />}
                      </FieldContent>
                      <Select
                        name={field.name}
                        value={field.state.value}
                        onValueChange={field.handleChange}
                      >
                        <SelectTrigger id={field.name} className="w-full" aria-invalid={isInvalid}>
                          <SelectValue placeholder="Sélectionner un type" />
                        </SelectTrigger>
                        <SelectContent position="item-aligned">
                          {Object.entries(EMPLOYMENT_TYPE).map(([value, label]) => (
                            <SelectItem key={value} value={value}>
                              {label}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </Field>
                  )
                }}
              </form.AppField>

              <JobDashboardTitleSlugFields form={form} autoSlug={autoSlug} />

              <form.AppField name="summary">
                {(field) => {
                  const isInvalid = field.state.meta.isTouched && !field.state.meta.isValid
                  return (
                    <Field data-invalid={isInvalid}>
                      <FieldLabel htmlFor={field.name}>Description</FieldLabel>
                      <Textarea
                        id={field.name}
                        name={field.name}
                        value={field.state.value}
                        onBlur={field.handleBlur}
                        onChange={(e) => field.handleChange(e.target.value)}
                        aria-invalid={isInvalid}
                        placeholder="Courte description de l'emploi..."
                        rows={3}
                      />
                      {isInvalid && <FieldError errors={field.state.meta.errors} />}
                    </Field>
                  )
                }}
              </form.AppField>

              <JobDashboardAffiliationFields form={form} />

              <form.AppField name="salary">
                {(field) => {
                  const isInvalid = field.state.meta.isTouched && !field.state.meta.isValid
                  return (
                    <Field data-invalid={isInvalid}>
                      <FieldLabel htmlFor={field.name}>Salaire hebdomadaire *</FieldLabel>
                      <NumberField
                        id={field.name}
                        name={field.name}
                        value={field.state.value}
                        onBlur={field.handleBlur}
                        onChange={(v) => {
                          if (v) {
                            field.handleChange(v)
                          } else {
                            field.handleChange(undefined as unknown as number)
                          }
                        }}
                        aria-invalid={isInvalid}
                        min={0}
                        formatOptions={{
                          style: 'currency',
                          currency: 'USD',
                          currencyDisplay: 'symbol',
                          currencySign: 'accounting',
                        }}
                        className="gap-2"
                      >
                        <NumberFieldContent>
                          <NumberFieldDecrement />
                          <NumberFieldInput />
                          <NumberFieldIncrement />
                        </NumberFieldContent>
                      </NumberField>
                      {isInvalid && <FieldError errors={field.state.meta.errors} />}
                    </Field>
                  )
                }}
              </form.AppField>

              <JobDashboardResponsibilitiesField form={form} />

              <JobDashboardRequirementsField form={form} />

              <JobDashboardSkillsField form={form} />
            </CardContent>
          </Card>
        </div>

        <JobDashboardFormSidebar form={form} variant={variant} formId={id} />
      </div>
    )
  },
})
