// inertia/features/jobs/components/form/dashboard/fields/job-dashboard-affiliation-fields.tsx
import { createJobFormOpts } from '@/features/jobs/constants/form_opts'
import { withForm } from '@/shared/hooks/form'
import {
  Field,
  FieldContent,
  FieldDescription,
  FieldError,
  FieldLabel,
} from '@/shared/components/ui/field'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/shared/components/ui/select'
import { DEPARTMENTS } from '@/shared/constants/departments.constants'
import { Input } from '@/shared/components/ui/input'

export const JobDashboardAffiliationFields = withForm({
  ...createJobFormOpts,
  render: ({ form }) => {
    return (
      <>
        <form.AppField name="department">
          {(field) => {
            const isInvalid = field.state.meta.isTouched && !field.state.meta.isValid
            return (
              <Field orientation="responsive" data-invalid={isInvalid}>
                <FieldContent>
                  <FieldLabel htmlFor={field.name}>Département *</FieldLabel>
                  {isInvalid && <FieldError errors={field.state.meta.errors} />}
                </FieldContent>
                <Select
                  name={field.name}
                  value={field.state.value}
                  onValueChange={field.handleChange}
                >
                  <SelectTrigger id={field.name} className="w-full" aria-invalid={isInvalid}>
                    <SelectValue placeholder="Sélectionner un département" />
                  </SelectTrigger>
                  <SelectContent position="item-aligned">
                    {DEPARTMENTS.sort((a, b) => {
                      const textA = a.title.toUpperCase()
                      const textB = b.title.toUpperCase()
                      return textA < textB ? -1 : textA > textB ? 1 : 0
                    }).map((dep) => (
                      <SelectItem key={dep.id} value={dep.id}>
                        {dep.title}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </Field>
            )
          }}
        </form.AppField>

        <form.AppField name="reportsTo">
          {(field) => {
            const isInvalid = field.state.meta.isTouched && !field.state.meta.isValid
            return (
              <Field data-invalid={isInvalid}>
                <FieldLabel htmlFor={field.name}>Relève de *</FieldLabel>
                <Input
                  id={field.name}
                  name={field.name}
                  value={field.state.value}
                  onBlur={field.handleBlur}
                  onChange={(e) => field.handleChange(e.target.value)}
                  aria-invalid={isInvalid}
                  placeholder="Directeur des Ressources Humaines"
                />
                <FieldDescription>Nom de la fonction du responsable direct</FieldDescription>
                {isInvalid && <FieldError errors={field.state.meta.errors} />}
              </Field>
            )
          }}
        </form.AppField>
      </>
    )
  },
})

// inertia/features/jobs/components/form/dashboard/JobDashboardAffiliationFields.vue
<template>
  <VeeField v-slot="{ field, errors }" name="department">
    <Field orientation="responsive" :data-invalid="!!errors.length">
      <FieldContent>
        <FieldLabel :for="field.name">Département *</FieldLabel>
        <FieldError v-if="errors.length" :errors="errors" />
      </FieldContent>
      <Select :model-value="field.value" @update:model-value="field.onChange" @blur="field.onBlur">
        <SelectTrigger :id="field.name" class="w-full" :aria-invalid="!!errors.length">
          <SelectValue placeholder="Sélectionner un département" />
        </SelectTrigger>
        <SelectContent position="item-aligned">
          <SelectItem
            v-for="department in DEPARTMENTS.sort((a, b) => {
              const textA = a.title.toUpperCase()
              const textB = b.title.toUpperCase()
              return textA < textB ? -1 : textA > textB ? 1 : 0
            })"
            :key="department.id"
            :value="department.id"
          >
            {{ department.title }}
          </SelectItem>
        </SelectContent>
      </Select>
    </Field>
  </VeeField>

  <VeeField v-slot="{ field, errors }" name="reportsTo">
    <Field :data-invalid="!!errors.length">
      <FieldLabel :for="field.name">Relève de *</FieldLabel>
      <Input
        :id="field.name"
        :model-value="field.value"
        @update:model-value="field.onChange"
        @blur="field.onBlur"
        placeholder="Directeur des Ressources Humaines"
        :aria-invalid="!!errors.length"
      />
      <FieldDescription>Nom de la fonction du responsable direct</FieldDescription>
      <FieldError v-if="errors.length" :errors="errors" />
    </Field>
  </VeeField>
</template>

<script setup lang="ts">
import { Field as VeeField } from 'vee-validate'
import { DEPARTMENTS } from '@/shared/constants/departments.constants'
import {
  Field,
  FieldContent,
  FieldDescription,
  FieldError,
  FieldLabel,
} from '@/shared/components/ui/field'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/shared/components/ui/select'
import { Input } from '@/shared/components/ui/input'
</script>
