// inertia/pages/errors/not_found.vue
<template>
  <Head title="Error 404" />

  <div class="my-60 text-center">
    <h1 class="text-4xl md:text-5xl font-bold mb-4 font-serif">Page not found</h1>
    <p class="text-xl opacity-90">This page does not exist.</p>
  </div>
</template>
<script setup lang="ts">
import Head from '@/shared/components/AppHead.vue'
</script>

// inertia/pages/errors/not-found.tsx
import Head from '@/shared/components/app-head'

export default function ServerError() {
  return (
    <>
      <Head title="Page introuvable" />

      <div className="my-60 text-center">
        <h1 className="text-4xl md:text-5xl font-bold mb-4 font-serif">Page introuvable</h1>
        <p className="text-xl opacity-90">Cette page n'existe pas ou plus.</p>
      </div>
    </>
  )
}
