// inertia/pages/errors/server-error.tsx
import Head from '@/shared/components/app-head'

export default function ServerError() {
  return (
    <>
      <Head title="Une erreur est survenue" />

      <div className="my-60 text-center">
        <h1 className="text-4xl md:text-5xl font-bold mb-4 font-serif">Erreur serveur</h1>
        <p className="text-xl opacity-90">Un problème est survenu. Veuillez réessayer plus tard.</p>
      </div>
    </>
  )
}

// inertia/pages/errors/server_error.vue
<script setup lang="ts">
import Head from '@/shared/components/AppHead.vue'

defineProps<{ error: any }>()
</script>

<template>
  <Head title="Error 404" />

  <div class="my-60 text-center">
    <h1 class="text-4xl md:text-5xl font-bold mb-4 font-serif">Server Error</h1>
    <p class="text-xl opacity-90">{{ error?.message }}</p>
  </div>
</template>
